export const tailwindComponents = {
  ".alert>:not([hidden])~:not([hidden])": {},
  ".alert": {},
  "@media (min-width:768px)": {},
  ".alert>*": {},
  ".artboard": {},
  ".avatar": {},
  ".avatar>div": {},
  ".avatar img": {},
  ".avatar.placeholder>div": {},
  ".badge": {},
  ".breadcrumbs": {},
  ".breadcrumbs>ul": {},
  ".breadcrumbs>ul>li": {},
  ".breadcrumbs>ul>li>a": {},
  ".breadcrumbs>ul>li>a:hover": {},
  ".btn": {},
  ".btn:focus": {},
  ".btn-disabled,.btn[disabled]": {},
  ".btn-square": {},
  ".btn-circle": {},
  ".btn.loading,.btn.loading:hover": {},
  ".btn.loading:before": {},
  "@media (prefers-reduced-motion:reduce)": {},
  "@-webkit-keyframes spin": {},
  "@keyframes spin": {},
  ".btn-group": {},
  ".btn-group>input[type=radio].btn": {},
  ".btn-group>input[type=radio].btn:before": {},
  ".card": {},
  ".card:focus": {},
  ".card-body": {},
  ".card figure,.card figure>*": {},
  ".card-actions": {},
  ".card-actions>*": {},
  ".card.image-full": {},
  ".card.image-full:before": {},
  ".card.image-full:before,.card.image-full>*": {},
  ".card.image-full>figure img": {},
  ".card.image-full>.card-body": {},
  ".carousel": {},
  ".carousel-vertical": {},
  ".carousel-item": {},
  ".carousel-center .carousel-item": {},
  ".carousel-end .carousel-item": {},
  ".checkbox:focus": {},
  ".collapse": {},
  ".collapse-content,.collapse-title,.collapse>input[type=checkbox]": {},
  ".collapse>input[type=checkbox]": {},
  ".collapse-content": {},
  ".collapse-open .collapse-content,.collapse:focus:not(.collapse-close) .collapse-content,.collapse:not(.collapse-close) input[type=checkbox]:checked~.collapse-content":
    {},
  ":root .countdown": {},
  ".countdown": {},
  ".countdown>*": {},
  ".countdown>:before": {},
  ".divider": {},
  ".divider:after,.divider:before": {},
  ".drawer": {},
  ".drawer.drawer-end .drawer-toggle~.drawer-side>.drawer-overlay+*": {},
  ".drawer.drawer-end .drawer-toggle:checked~.drawer-side>.drawer-overlay+*":
    {},
  ".drawer-toggle": {},
  ".drawer-toggle~.drawer-content": {},
  ".drawer-toggle~.drawer-side": {},
  ".drawer-toggle~.drawer-side>.drawer-overlay": {},
  ".drawer-toggle~.drawer-side>.drawer-overlay+*": {},
  ".drawer-toggle:checked~.drawer-side": {},
  ".drawer-toggle:checked~.drawer-side>.drawer-overlay": {},
  ".drawer-toggle:checked~.drawer-side>.drawer-overlay+*": {},
  "@media (min-width:1024px)": {},
  ".dropdown": {},
  ".dropdown>:focus": {},
  ".dropdown .dropdown-content": {},
  ".dropdown-end .dropdown-content": {},
  ".dropdown-left .dropdown-content": {},
  ".dropdown-right .dropdown-content": {},
  ".dropdown-top .dropdown-content": {},
  ".dropdown-end.dropdown-right .dropdown-content": {},
  ".dropdown-end.dropdown-left .dropdown-content": {},
  ".dropdown.dropdown-hover:hover .dropdown-content,.dropdown.dropdown-open .dropdown-content,.dropdown:not(.dropdown-hover):focus-within .dropdown-content,.dropdown:not(.dropdown-hover):focus .dropdown-content":
    {},
  ".form-control": {},
  ".label": {},
  ".hero": {},
  ".hero>*": {},
  ".hero-overlay": {},
  ".hero-content": {},
  ".indicator": {},
  ".indicator .indicator-item": {},
  ".indicator .indicator-item.indicator-start": {},
  ".indicator .indicator-item.indicator-center": {},
  ".indicator .indicator-item.indicator-end": {},
  ".indicator .indicator-item.indicator-bottom": {},
  ".indicator .indicator-item.indicator-middle": {},
  ".indicator .indicator-item.indicator-top": {},
  ".input": {},
  ".input:focus": {},
  ".kbd": {},
  ".link": {},
  ".link-hover": {},
  ".link-hover:hover": {},
  ".mask": {},
  ".menu": {},
  ".menu.horizontal": {},
  ".menu.horizontal li": {},
  ".menu li": {},
  ".menu li>a,.menu li>span": {},
  ".menu li>a": {},
  ".menu li>a:focus": {},
  ".menu li.disabled>a,.menu li.disabled>span": {},
  ".mockup-code": {},
  ".mockup-code pre[data-prefix]:before": {},
  ".mockup-window": {},
  ".mockup-window pre[data-prefix]:before": {},
  ".modal": {},
  "@media (min-width:640px)": {},
  ".modal-toggle:checked~.modal,.modal:target": {},
  ".modal-action": {},
  ".modal-toggle": {},
  ".navbar": {},
  ".navbar>*": {},
  ".navbar-start": {},
  ".navbar-center": {},
  ".navbar-end": {},
  ".progress": {},
  ".radio:focus": {},
  ".range": {},
  ".range:focus": {},
  ".select": {},
  ".select:focus": {},
  ".select-disabled,.select[disabled]": {},
  ".stack": {},
  ".stack>*": {},
  ".stack>:nth-child(2)": {},
  ".stack>:first-child": {},
  ".stats": {},
  ".stat": {},
  ".stat-figure": {},
  ".stat-title": {},
  ".stat-value": {},
  ".stat-desc": {},
  ".stat-actions": {},
  ".stats.grid-flow-row": {},
  ".steps": {},
  ".steps .step": {},
  ".tabs": {},
  ".tab": {},
  ".table": {},
  ".table th:first-child": {},
  ".textarea": {},
  ".textarea:focus": {},
  ".toggle:focus": {},
  ".tooltip": {},
  ".tooltip:before": {},
  ".tooltip-bottom:before": {},
  ".tooltip-left:before": {},
  ".tooltip-right:before": {},
  ".avatar-group": {},
  ".avatar-group .avatar": {},
  ".btn .badge": {},
  ".btn .badge-outline": {},
  ".btn-outline .badge": {},
  ".btn-outline.btn-primary .badge": {},
  ".btn-outline.btn-secondary .badge": {},
  ".btn-outline.btn-accent .badge": {},
  ".btn-outline .badge.outline": {},
  ".btn-outline.btn-primary .badge-outline": {},
  ".btn-outline.btn-secondary .badge-outline": {},
  ".btn-outline.btn-accent .badge-outline": {},
  ".btn-outline:hover .badge": {},
  ".btn-outline:hover .badge.outline": {},
  ".btn-outline.btn-primary:hover .badge": {},
  ".btn-outline.btn-primary:hover .badge.outline": {},
  ".btn-outline.btn-secondary:hover .badge": {},
  ".btn-outline.btn-secondary:hover .badge.outline": {},
  ".btn-outline.btn-accent:hover .badge": {},
  ".btn-outline.btn-accent:hover .badge.outline": {},
  ".breadcrumbs>ul>li>a:focus": {},
  ".breadcrumbs>ul>li>a:focus-visible": {},
  ".breadcrumbs>ul>li+:before": {},
  ".btn:active:focus,.btn:active:hover": {},
  ".btn-active,.btn:hover": {},
  ".btn:focus-visible": {},
  ".btn-primary": {},
  ".btn-primary.btn-active,.btn-primary:hover": {},
  ".btn-primary:focus-visible": {},
  ".btn-secondary": {},
  ".btn-secondary.btn-active,.btn-secondary:hover": {},
  ".btn-secondary:focus-visible": {},
  ".btn-accent": {},
  ".btn-accent.btn-active,.btn-accent:hover": {},
  ".btn-accent:focus-visible": {},
  ".btn-info": {},
  ".btn-info.btn-active,.btn-info:hover": {},
  ".btn-info:focus-visible": {},
  ".btn-success": {},
  ".btn-success.btn-active,.btn-success:hover": {},
  ".btn-success:focus-visible": {},
  ".btn-warning": {},
  ".btn-warning.btn-active,.btn-warning:hover": {},
  ".btn-warning:focus-visible": {},
  ".btn-error": {},
  ".btn-error.btn-active,.btn-error:hover": {},
  ".btn-error:focus-visible": {},
  ".btn-notice": {},
  ".btn-notice.btn-active,.btn-notice:hover": {},
  ".btn-notice:focus-visible": {},
  ".btn.glass.btn-active,.btn.glass:hover": {},
  ".btn.glass:focus-visible": {},
  ".btn-ghost": {},
  ".btn-ghost.btn-active,.btn-ghost:hover": {},
  ".btn-ghost:focus-visible": {},
  ".btn-link": {},
  ".btn-link.btn-active,.btn-link:hover": {},
  ".btn-link:focus-visible": {},
  ".btn-outline": {},
  ".btn-outline:hover": {},
  ".btn-outline.btn-primary": {},
  ".btn-outline.btn-primary:hover": {},
  ".btn-outline.btn-secondary": {},
  ".btn-outline.btn-secondary:hover": {},
  ".btn-outline.btn-accent": {},
  ".btn-outline.btn-accent:hover": {},
  ".btn.loading.btn-circle:before,.btn.loading.btn-square:before": {},
  ".btn.loading.btn-lg:before,.btn.loading.btn-xl:before": {},
  ".btn.loading.btn-sm:before,.btn.loading.btn-xs:before": {},
  ".btn-group>.btn-active,.btn-group>input[type=radio]:checked.btn": {},
  ".btn-group>.btn-active:focus-visible,.btn-group>input[type=radio]:checked.btn:focus-visible":
    {},
  ".btn-group>.btn:not(:first-child)": {},
  ".btn-group>.btn:not(:last-child)": {},
  "@-webkit-keyframes button-pop": {},
  "@keyframes button-pop": {},
  ".card:focus-visible": {},
  ".card.bordered": {},
  ".card.compact .card-body": {},
  ".card.compact .card-title": {},
  ".card-title": {},
  ".card-actions:first-child": {},
  ".card-actions:last-child": {},
  ".carousel::-webkit-scrollbar": {},
  ".checkbox": {},
  ".checkbox:focus-visible": {},
  ".checkbox:checked": {},
  ".checkbox-primary": {},
  ".checkbox-primary:hover": {},
  ".checkbox-primary:focus-visible": {},
  ".checkbox-primary:checked": {},
  ".checkbox-secondary": {},
  ".checkbox-secondary:hover": {},
  ".checkbox-secondary:focus-visible": {},
  ".checkbox-secondary:checked": {},
  ".checkbox-accent": {},
  ".checkbox-accent:hover": {},
  ".checkbox-accent:focus-visible": {},
  ".checkbox-accent:checked": {},
  ".checkbox:disabled": {},
  "@-webkit-keyframes checkmark": {},
  "@keyframes checkmark": {},
  ".checkbox-mark": {},
  ".collapse-arrow .collapse-title:after": {},
  ".collapse-plus .collapse-title:after": {},
  ".collapse:not(.collapse-open):not(.collapse-close) .collapse-title,.collapse:not(.collapse-open):not(.collapse-close) input[type=checkbox]":
    {},
  ".collapse:focus:not(.collapse-open):not(.collapse-close) .collapse-title":
    {},
  ".collapse-title,.collapse>input[type=checkbox]": {},
  ".collapse:not(.collapse-close) input[type=checkbox]:focus~.collapse-title":
    {},
  ".collapse-open .collapse-title,.collapse:focus:not(.collapse-close) .collapse-title,.collapse:not(.collapse-close) input[type=checkbox]:checked~.collapse-title":
    {},
  ".collapse-arrow:focus:not(.collapse-close) .collapse-title:after,.collapse-arrow:not(.collapse-close) input[type=checkbox]:checked~.collapse-title:after,.collapse-open.collapse-arrow .collapse-title:after":
    {},
  ".collapse-open.collapse-plus .collapse-title:after,.collapse-plus:focus:not(.collapse-close) .collapse-title:after,.collapse-plus:not(.collapse-close) input[type=checkbox]:checked~.collapse-title:after":
    {},
  ".divider:not(:empty):before": {},
  ".divider:not(:empty):after": {},
  ".drawer.drawer-end .drawer-toggle:checked~.drawer-content": {},
  ".drawer-toggle:checked~.drawer-content": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-primary": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-secondary":
    {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-accent": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-info": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-success": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-warning": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-error": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-notice": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.glass": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-ghost": {},
  ".drawer-toggle:focus-visible~.drawer-content .drawer-button.btn-link": {},
  ".dropdown.dropdown-hover:hover .dropdown-content,.dropdown.dropdown-open .dropdown-content,.dropdown:focus-within .dropdown-content,.dropdown:focus .dropdown-content":
    {},
  ".label-text": {},
  ".label-text-alt": {},
  ".label a:hover": {},
  ".input-bordered": {},
  ".input-ghost": {},
  ".input-ghost:focus": {},
  ".input-primary": {},
  ".input-primary:focus": {},
  ".input-secondary": {},
  ".input-secondary:focus": {},
  ".input-accent": {},
  ".input-accent:focus": {},
  ".input-info": {},
  ".input-info:focus": {},
  ".input-success": {},
  ".input-success:focus": {},
  ".input-warning": {},
  ".input-warning:focus": {},
  ".input-error": {},
  ".input-error:focus": {},
  ".input-notice": {},
  ".input-notice:focus": {},
  ".input-disabled,.input[disabled]": {},
  ".input-disabled::-moz-placeholder,.input[disabled]::-moz-placeholder": {},
  ".input-disabled:-ms-input-placeholder,.input[disabled]:-ms-input-placeholder":
    {},
  ".input-disabled::placeholder,.input[disabled]::placeholder": {},
  ".link-primary": {},
  ".link-primary:hover": {},
  ".link-secondary": {},
  ".link-secondary:hover": {},
  ".link-accent": {},
  ".link-accent:hover": {},
  ".link-neutral": {},
  ".link-neutral:hover": {},
  ".link:focus": {},
  ".link:focus-visible": {},
  ".mask-squircle": {},
  ".mask-decagon": {},
  ".mask-diamond": {},
  ".mask-heart": {},
  ".mask-hexagon": {},
  ".mask-hexagon-2": {},
  ".mask-circle": {},
  ".mask-parallelogram": {},
  ".mask-parallelogram-2": {},
  ".mask-parallelogram-3": {},
  ".mask-parallelogram-4": {},
  ".mask-pentagon": {},
  ".mask-square": {},
  ".mask-star": {},
  ".mask-star-2": {},
  ".mask-triangle": {},
  ".mask-triangle-2": {},
  ".mask-triangle-3": {},
  ".mask-triangle-4": {},
  ".menu.horizontal li.bordered>a,.menu.horizontal li.bordered>span": {},
  ".menu[class*=p-] li a": {},
  ".menu li>a:focus,.menu li>a:hover": {},
  ".menu li>a.active": {},
  ".menu li>a:active": {},
  ".menu li.disabled>a:hover,.menu li.disabled>span:hover": {},
  ".menu li.bordered a,.menu li.bordered span": {},
  ".menu li.hover-bordered a": {},
  ".menu li.hover-bordered a:hover": {},
  ".menu ul": {},
  ".menu.compact li>a,.menu.compact li>span": {},
  ".menu .menu-title>a,.menu .menu-title>span": {},
  ".mockup-code:before": {},
  ".mockup-code pre:before": {},
  ".mockup-window:before": {},
  ".mockup-phone": {},
  ".mockup-phone .camera": {},
  ".mockup-phone .camera:before": {},
  ".mockup-phone .camera:after": {},
  ".mockup-phone .display": {},
  ".modal-box": {},
  ".modal-toggle:checked~.modal .modal-box,.modal:target .modal-box": {},
  ".modal-action>:not([hidden])~:not([hidden])": {},
  ".progress::-moz-progress-bar": {},
  ".progress-primary::-moz-progress-bar": {},
  ".progress-secondary::-moz-progress-bar": {},
  ".progress-accent::-moz-progress-bar": {},
  ".progress-info::-moz-progress-bar": {},
  ".progress-success::-moz-progress-bar": {},
  ".progress-warning::-moz-progress-bar": {},
  ".progress-error::-moz-progress-bar": {},
  ".progress-notice::-moz-progress-bar": {},
  ".progress::-webkit-progress-bar": {},
  ".progress::-webkit-progress-value": {},
  ".progress-primary::-webkit-progress-value": {},
  ".progress-secondary::-webkit-progress-value": {},
  ".progress-accent::-webkit-progress-value": {},
  ".progress-info::-webkit-progress-value": {},
  ".progress-success::-webkit-progress-value": {},
  ".progress-warning::-webkit-progress-value": {},
  ".progress-error::-webkit-progress-value": {},
  ".progress-notice::-webkit-progress-value": {},
  ".radio": {},
  ".radio:focus-visible": {},
  ".radio:checked": {},
  ".radio-primary": {},
  ".radio-primary:hover": {},
  ".radio-primary:focus-visible": {},
  ".radio-primary:checked": {},
  ".radio-secondary": {},
  ".radio-secondary:hover": {},
  ".radio-secondary:focus-visible": {},
  ".radio-secondary:checked": {},
  ".radio-accent": {},
  ".radio-accent:hover": {},
  ".radio-accent:focus-visible": {},
  ".radio-accent:checked": {},
  ".radio:disabled": {},
  "@-webkit-keyframes radiomark": {},
  "@keyframes radiomark": {},
  ".radio-mark": {},
  ".range:focus-visible::-webkit-slider-thumb": {},
  ".range:focus-visible::-moz-range-thumb": {},
  ".range::-webkit-slider-runnable-track": {},
  ".range::-moz-range-track": {},
  ".range::-webkit-slider-thumb": {},
  ".range::-moz-range-thumb": {},
  ".range-primary": {},
  ".range-secondary": {},
  ".range-accent": {},
  ".slider": {},
  ".slider-primary": {},
  ".slider-secondary": {},
  ".slider-accent": {},
  ".slider-info": {},
  ".slider-success": {},
  ".slider-warning": {},
  ".slider-error": {},
  ".slider-notice": {},
  ".slider-primary:focus": {},
  ".slider-secondary:focus": {},
  ".slider-accent:focus": {},
  ".slider-info:focus": {},
  ".slider-success:focus": {},
  ".slider-warning:focus": {},
  ".slider-error:focus": {},
  ".slider-notice:focus": {},
  ".select-bordered": {},
  ".select-ghost": {},
  ".select-ghost:focus": {},
  ".select-primary": {},
  ".select-primary:focus": {},
  ".select-secondary": {},
  ".select-secondary:focus": {},
  ".select-accent": {},
  ".select-accent:focus": {},
  ".select-info": {},
  ".select-info:focus": {},
  ".select-success": {},
  ".select-success:focus": {},
  ".select-warning": {},
  ".select-warning:focus": {},
  ".select-error": {},
  ".select-error:focus": {},
  ".select-notice": {},
  ".select-notice:focus": {},
  ".select-disabled::-moz-placeholder,.select[disabled]::-moz-placeholder": {},
  ".select-disabled:-ms-input-placeholder,.select[disabled]:-ms-input-placeholder":
    {},
  ".select-disabled::placeholder,.select[disabled]::placeholder": {},
  ".list-group-item": {},
  ".list-group-item.selected": {},
  ".list-group-item.disabled": {},
  ".list-group-item:disabled": {},
  ".list-group-item.list-group-item-small": {},
  ".stat+.stat": {},
  ".stats.grid-flow-row .stat+.stat": {},
  ".steps .step:before": {},
  ".steps .step:after": {},
  ".steps .step:first-child:before": {},
  ".steps .step[data-content]:after": {},
  ".steps .step-neutral+.step-neutral:before,.steps .step-neutral:after": {},
  ".steps .step-primary+.step-primary:before,.steps .step-primary:after": {},
  ".steps .step-secondary+.step-secondary:before,.steps .step-secondary:after":
    {},
  ".steps .step-accent+.step-accent:before,.steps .step-accent:after": {},
  ".steps .step-info+.step-info:before": {},
  ".steps .step-info:after": {},
  ".steps .step-success+.step-success:before": {},
  ".steps .step-success:after": {},
  ".steps .step-warning+.step-warning:before": {},
  ".steps .step-warning:after": {},
  ".steps .step-error+.step-error:before": {},
  ".steps .step-error:after": {},
  ".steps .step-notice+.step-notice:before": {},
  ".steps .step-notice:after": {},
  ".tab:hover": {},
  ".tab.tab-active": {},
  ".tab:focus": {},
  ".tab:focus-visible": {},
  ".tab-bordered": {},
  ".tab-lifted": {},
  ".tab-lifted.tab-active": {},
  ".tab-lifted.tab-active:after,.tab-lifted.tab-active:before": {},
  ".tab-lifted.tab-active:before": {},
  "[dir=rtl] .tab-lifted.tab-active:before": {},
  ".tab-lifted.tab-active:after": {},
  "[dir=rtl] .tab-lifted.tab-active:after": {},
  ".tab-lifted.tab-active:first-child:before": {},
  ".tab-lifted.tab-active:last-child:after": {},
  ".tab-lifted.tab-active+.tab-lifted.tab-active:before": {},
  ".tabs-boxed": {},
  ".tabs-boxed .tab-active": {},
  ".tabs-boxed .tab-active:hover": {},
  ".table td,.table th": {},
  ".table tr.active:nth-child(2n) td,.table tr.active:nth-child(2n) th,.table tr.active td,.table tr.active th":
    {},
  ".table tr.hover:hover td,.table tr.hover:hover th,.table tr.hover:nth-child(2n):hover td,.table tr.hover:nth-child(2n):hover th":
    {},
  ".table:not(.table-zebra) tbody tr:not(:last-child) td,.table:not(.table-zebra) tbody tr:not(:last-child) th,.table:not(.table-zebra) tfoot tr:not(:last-child) td,.table:not(.table-zebra) tfoot tr:not(:last-child) th,.table:not(.table-zebra) thead tr:not(:last-child) td,.table:not(.table-zebra) thead tr:not(:last-child) th":
    {},
  ".table tfoot td,.table tfoot th,.table thead td,.table thead th": {},
  ".table tfoot td:first-child,.table tfoot th:first-child,.table thead td:first-child,.table thead th:first-child":
    {},
  ".table tfoot td:last-child,.table tfoot th:last-child,.table thead td:last-child,.table thead th:last-child":
    {},
  ".table tbody td,.table tbody th": {},
  ".table-zebra tbody tr td:first-child,.table-zebra tbody tr th:first-child":
    {},
  ".table-zebra tbody tr td:last-child,.table-zebra tbody tr th:last-child": {},
  ".table-zebra tbody tr:nth-child(2n) td,.table-zebra tbody tr:nth-child(2n) th":
    {},
  ".table-compact td,.table-compact th": {},
  ".textarea-bordered": {},
  ".textarea-ghost": {},
  ".textarea-ghost:focus": {},
  ".textarea-primary": {},
  ".textarea-primary:focus": {},
  ".textarea-secondary": {},
  ".textarea-secondary:focus": {},
  ".textarea-accent": {},
  ".textarea-accent:focus": {},
  ".textarea-info": {},
  ".textarea-info:focus": {},
  ".textarea-success": {},
  ".textarea-success:focus": {},
  ".textarea-warning": {},
  ".textarea-warning:focus": {},
  ".textarea-error": {},
  ".textarea-error:focus": {},
  ".textarea-notice": {},
  ".textarea-notice:focus": {},
  ".textarea-disabled,.textarea[disabled]": {},
  ".textarea-disabled::-moz-placeholder,.textarea[disabled]::-moz-placeholder":
    {},
  ".textarea-disabled:-ms-input-placeholder,.textarea[disabled]:-ms-input-placeholder":
    {},
  ".textarea-disabled::placeholder,.textarea[disabled]::placeholder": {},
  ".toggle": {},
  ".toggle:focus-visible": {},
  ".toggle:checked": {},
  "[dir=rtl] .toggle:checked": {},
  ".toggle-primary:focus-visible": {},
  ".toggle-primary:checked": {},
  ".toggle-secondary:focus-visible": {},
  ".toggle-secondary:checked": {},
  ".toggle-accent:focus-visible": {},
  ".toggle-accent:checked": {},
  ".toggle:disabled": {},
  ".toggle-mark": {},
  ".tooltip:after,.tooltip:before": {},
  ".tooltip:after": {},
  ".tooltip.tooltip-open:after,.tooltip.tooltip-open:before,.tooltip:hover:after,.tooltip:hover:before":
    {},
  ".tooltip-bottom:after": {},
  ".tooltip-left:after": {},
  ".tooltip-right:after": {},
  ".tooltip-primary": {},
  ".tooltip-secondary": {},
  ".tooltip-accent": {},
  ".tooltip-info": {},
  ".tooltip-success": {},
  ".tooltip-warning": {},
  ".tooltip-error": {},
  ".tooltip-notice": {},
  ".prose": {},
  ".prose .lead,.prose a,.prose a code,.prose blockquote,.prose figure figcaption,.prose h1,.prose h2,.prose h3,.prose h4,.prose strong,.prose thead":
    {},
  ".prose .lead:hover,.prose a:hover,.prose a code:hover,.prose blockquote:hover,.prose figure figcaption:hover,.prose h1:hover,.prose h2:hover,.prose h3:hover,.prose h4:hover,.prose strong:hover,.prose thead:hover":
    {},
  ".prose code": {},
  ".prose pre": {},
  ".prose pre code": {},
  ".prose code:after,.prose code:before": {},
  ".prose ol>li:before,.prose ol>li:hover:before": {},
  ".prose blockquote": {},
  ".prose ul>li:before": {},
  ".prose thead": {},
  ".prose tbody tr": {},
  ".faded-scroll-x": {},
  ".faded-scroll-y": {},
  ".animate-spin-step": {},
  ".panel-bordered": {},
  ".panel-ghost": {},
  ".panel-primary": {},
  ".panel-secondary": {},
  ".panel-accent": {},
  ".panel-info": {},
  ".panel-success": {},
  ".panel-warning": {},
  ".panel-error": {},
  ".panel-notice": {},
};
