// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	MyServer: DurableObjectNamespace<import("./app/cloudflareServer").MyServer>;
	assets: R2Bucket;
}
