import {duplicateList, concat} from "./utils";

export default {
  digit: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
  letter: [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ],
  adjectives: [
    "Green",
    "Blue",
    "White",
    "Black",
    "Violet",
    "Indigo",
    "Lilac",
    "Azure",
    "Grey",
    "Golden",
    "Marigold",
    "Lavender",
    "Alabaster",
    "Vermillion",
    "Ivory",
    "Shimmering",
    "Rainbow",
    "Emerald",
    "Sapphire",
    "Dark",
    "Poor",
    "Lonely",
    "Glorious",
    "Magnificent",
    "Intrepid",
    "Bold",
    "Courageous",
    "Generous",
    "Brazen",
    "Resolute",
    "Reliable",
    "Battered",
    "Sensible",
    "Defiant",
    "Stoic",
    "Bittersweet",
    "Great",
    "Cautious",
    "Careful",
    "Spicy",
    "Lucky",
    "Pious",
    "Faithful",
    "Adventurous",
    "Merry",
    "Joyous",
    "Stalwart",
    "Wealthy",
    "Favorite",
    "Windswept",
    "Forgotten",
    "Unlucky",
    "Radiant",
    "Hopeful",
    "Distant",
    "Clever",
    "Honorable",
    "Radical",
    "Slippery",
    "Northern",
    "Southern",
    "Eastern",
    "Western",
    "Deepwater",
    "Blessed",
    "Valiant",
    "Noble",
    "Thoughtful",
    "Steely",
    "Sanguine",
    "Sunny",
    "Chiseled",
    "Stormy",
    "Endless",
    "Infinite",
    "Diligent",
    "Patient",
    "Wistful",
    "Wise",
    "Graceful",
    "Subtle",
    "Broken",
    "Mighty",
    "Precious",
    "Misty",
    "Cold",
    "Stern",
    "Triumphant",
    "Steady",
    "Old",
    "Lovely",
    "Chastened",
    "Happy",
    "Laughing",
    "Winged",
    "Calico",
    "Crackling",
    "Hidden",
    "Good",
    "Prodigal",
    "Heavy",
    "Arcane",
    "Forever",
    "Scattered",
    "Obsidian",
    "Last",
    "Elder",
    "Younger",
    "Fuzzy",
    "Exotic",
    "Quick",
    "Amazing",
    "Tiny",
    "Grand",
    "Icy",
    "Deep",
    "Sassy",
    "Stark",
    "Windy",
    "Snowy",
    "Fair",
    "Pure",
    "Loyal",
    "Inca",
    "Mayan",
    "Atlantean",
    "Roman",
    "Byzantine",
    "Zulu",
    "Maori",
    "Prussian",
    "Smoky",
    "Cloudy",
    "Silly",
    "Leaky",
    "African",
    "Etruscan",
    "Trojan",
    "Unknown",
    "Saucy",
    "Seawise",
    "Legendary",
    "Royal",
    "New",
    "Dreamy",
    "Peaceful",
    "Thorny",
    "Moorish",
    "Portside",
    "Starboard",
    "Topside",
  ],
  cardinalDirections: ["North", "South", "East", "West"],
  maleTitles: ["Lord", "Prince", "King", "Emperor", "Duke", "Baron", "Master"],
  femaleTitles: ["Lady", "Princess", "Queen", "Empress", "Duchess", "Mistress"],
  genderNeutralTitles: [
    "Saint",
    "Captain",
    "Champion",
    "Admiral",
    "Sovereign",
    "Commodore",
  ],
  maleNames: [
    "Henry",
    "Nelson",
    "Randall",
    "Ivan",
    "James",
    "Atanu",
    "George",
    "Arthur",
    "Caspian",
    "Canute",
    "Enki",
    "Richard",
    "John",
    "William",
    "Donald",
    "Samuel",
    "Khufu",
    "Edward",
    "Sargon",
    "Cyrus",
    "Darius",
    "Vipra",
    "Raja",
    "Ranpir",
    "Jayesh",
    "Shang",
    "Wu",
    "Xian",
    "Alan",
    "Logan",
    "Eric",
    "Malcolm",
    "Monty",
    "Dana",
    "Philip",
    "Isiah",
    "Nasser",
    "Rashid",
    "Ahmed",
    "Ari",
    "Waleed",
    "Mobutu",
    "Osamu",
    "Tarou",
    "Partha",
    "Salvador",
    "Zuhair",
    "Kenji",
    "Takeshi",
    "Hidekai",
    "Chen",
    "Mon Ping",
    "Ruslan",
    "Vladimir",
    "Fyodor",
    "Hammurabi",
    "Denton",
    "Xiang",
    "Zhong",
    "Bapu",
    "Kouadio",
    "Santiago",
    "Rafael",
    "Ignacio",
    "Bruno",
    "Martin",
    "Starbuck",
    "Xu",
    "Zeus",
    "Poseidon",
    "Perry",
    "Crockett",
    "Thomas",
    "Robert",
    "Paul",
    "Raymond",
    "Godwin",
    "Abraham",
    "Tycho",
    "Kane",
    "Loki",
    "Thor",
    "Archibald",
    "Oberon",
    "Julian",
    "Graham",
    "Mark",
    "Ayo",
    "Baako",
    "Kojo",
    "Yakouba",
    "Jones",
    "Yoshi",
    "Kazuo",
    "Aroon",
    "Chung",
    "Eun",
    "Guang",
    "Hyo",
    "Isamu",
    "Hong",
    "Hulin",
    "Jiro",
    "Kasem",
    "Quon",
    "Zhen",
    "Diogo",
    "Xyron",
    "Orpheus",
    "Pushkin",
    "Justinian",
    "Achilles",
    "Hayward",
    "Sejong",
    "Sirius",
    "Glenn",
    "Azad",
    "Khalil",
    "Ori",
    "Ravi",
    "Sirhan",
    "Zev",
  ],
  femaleNames: [
    "Mary",
    "Anne",
    "Genevieve",
    "Elizabeth",
    "Shanshan",
    "Yin",
    "Lu",
    "Bao",
    "Ling",
    "Shuang",
    "Maria",
    "Isabella",
    "Fiona",
    "Caroline",
    "Catherine",
    "Victoria",
    "Jane",
    "Emily",
    "Nefertiti",
    "Fatima",
    "Sophia",
    "Katerina",
    "Teresa",
    "Etana",
    "Awan",
    "Xena",
    "Zoe",
    "Jane",
    "River",
    "Aletheia",
    "Sara",
    "Zara",
    "Olympia",
    "Layla",
    "Surya",
    "Shira",
    "Anita",
    "Sato",
    "Mika",
    "Mariko",
    "Olga",
    "Jing",
    "Marianne",
    "Natalie",
    "Julia",
    "Faye",
    "Deirdre",
    "Jaina",
    "Isabel",
    "Katerina",
    "Neela",
    "Durga",
    "Devi",
    "Madhavi",
    "Kavya",
    "Pari",
    "Riya",
    "Amwe",
    "Nakoyan",
    "Akua",
    "Sofia",
    "Gloria",
    "Catalina",
    "Pilar",
    "Elena",
    "Athena",
    "Calypso",
    "Ingrid",
    "Alana",
    "Lori",
    "Diana",
    "Ellen",
    "Eva",
    "Rebecca",
    "Valerie",
    "Michelle",
    "Jolene",
    "Sally",
    "Beatrice",
    "Winnie",
    "Christine",
    "Evelyn",
    "Ramona",
    "Lin",
    "Harriet",
    "Janice",
    "Samantha",
    "Josephine",
    "Amara",
    "Delu",
    "Ife",
    "Songmi",
    "Mia",
    "Paula",
    "Andrea",
    "Hua",
    "Jia",
    "Lien",
    "Mako",
    "Misako",
    "Niyati",
    "Ren",
    "Saura",
    "Shima",
    "Ting",
    "Vanita",
    "Yeo",
    "Yon",
    "April",
    "Scarlet",
    "Rissa",
    "Abilene",
    "Ramona",
    "Marietta",
    "Henrietta",
    "Belinda",
    "Antigone",
    "Bernice",
    "Ishtar",
    "Shannon",
    "Iris",
    "Amina",
    "Khalida",
    "Najla",
    "Nayyirah",
    "Rana",
    "Samara",
    "Sura",
    "Zarifa",
    "Grace",
  ],
  singularNouns: [
    "Star",
    "Sun",
    "Sky",
    "Moon",
    "Nova",
    "Corona",
    "Photon",
    "Aurora",
    "Void",
    "Shockwave",
    "Cloud",
    "Nebula",
    "Quasar",
    "Pulsar",
    "Horizon",
    "Zenith",
    "Comet",
    "Flare",
    "Energy",
    "Galaxy",
    "Ring",
    "Blade",
    "Sword",
    "Light",
    "Flash",
    "Dance",
    "Flood",
    "Bounty",
    "Castle",
    "Temple",
    "Spirit",
    "Trail",
    "Flight",
    "Heart",
    "Pennant",
    "Harvest",
    "Nymph",
    "Mermaid",
    "Siren",
    "Anchor",
    "Hammerhead",
    "Lion",
    "Lioness",
    "Eagle",
    "Silhouette",
    "Guardian",
    "God",
    "Tower",
    "Pillar",
    "Hero",
    "Quest",
    "Journey",
    "Matrix",
    "Palace",
    "Pyramid",
    "Goblet",
    "Sunset",
    "Sunrise",
    "Fish",
    "Symbol",
    "Mark",
    "Realm",
    "Tree",
    "Crossing",
    "Shadow",
    "Swan",
    "Forge",
    "Banner",
    "Voyage",
    "Rose",
    "Song",
    "Raven",
    "Point",
    "Mountain",
    "Island",
    "Forest",
    "Carnation",
    "Gaze",
    "Ship",
    "Cave",
    "Phoenix",
    "Soul",
    "Teacup",
    "Muse",
    "Chest",
    "Courser",
    "Katana",
    "God",
    "Goddess",
    "Hoard",
    "Jumper",
    "Rider",
    "Chaser",
    "Dancer",
    "Seeker",
    "Explorer",
    "Lover",
    "Hunter",
    "Beater",
    "Racer",
    "Piercer",
    "Charger",
    "Speeder",
    "Falcon",
    "Paladin",
    "Cavalier",
    "Spear",
    "Surfer",
    "Strider",
    "Genie",
    "Caravan",
    "Dreamer",
    "Folly",
    "Money Pit",
    "Beauty",
    "Mule",
    "Work Horse",
    "Moneymaker",
    "Starship",
    "Hauler",
    "Beater",
    "Fortune",
    "Dream",
    "Pride",
    "Gamble",
    "Downfall",
    "Regret",
    "Savior",
    "Miracle",
    "Last Chance",
    "Last Stand",
    "Adventure",
    "Jewel",
    "Surprise",
    "Cutter",
    "Cruiser",
    "Spice",
    "Canyon",
    "Tiger",
    "Start",
    "Angel",
    "Son",
    "Boy",
    "Daughter",
    "Girl",
    "Arrow",
    "Bolt",
    "Scholar",
    "Home",
    "Namer",
    "Sting",
    "Apprentice",
    "Walrus",
    "Schooner",
    "Pony",
    "Stick",
    "Wallet",
    "Cone",
    "Carnival",
    "Crossing",
    "Chapel",
    "Echo",
    "Name",
    "Bear",
    "Storm",
    "Bucket",
    "Bilge",
    "Wheel",
    "Wizard",
    "Wall",
    "Unicorn",
    "Gem",
    "Oath",
    "Ghost",
    "Engine",
    "Scallop",
    "Kiwi",
    "Gambit",
    "Pearl",
    "Day",
    "Maid",
    "Mare",
    "Citadel",
    "Dart",
    "Giant",
    "Pioneer",
    "Freehold",
    "Sentry",
    "Sentinel",
    "Zephyr",
    "Terminus",
    "Pinecone",
    "Sickle",
    "Ladybug",
    "Enchantress",
    "Pilgrim",
    "Alligator",
    "Legend",
    "Cutter",
    "Dune",
    "Obelisk",
  ],
  pluralNouns: [
    "Men",
    "Women",
    "Stars",
    "Dreams",
    "Waves",
    "Dragons",
    "Secrets",
    "Whispers",
    "Storms",
    "Eyes",
    "Hands",
    "Riches",
    "Changes",
    "Worlds",
    "Words",
    "Echoes",
    "Winds",
    "Leaves",
    "Clouds",
    "Legends",
    "Sails",
    "Beasts",
    "Oceans",
    "Idols",
    "Faces",
    "Names",
    "Thoughts",
    "Roses",
    "Coins",
    "Cups",
    "Wands",
    "Swords",
    "Wings",
    "Tears",
    "Flags",
    "Scars",
    "Tongues",
    "Deeds",
    "Ways",
    "Means",
    "Mysteries",
    "Wonders",
    "Fools",
    "Souls",
    "Roots",
    "Fronds",
    "Branches",
    "Vines",
    "Flowers",
    "Stones",
    "Seas",
    "Smiles",
    "Bees",
    "Sounds",
    "Paths",
    "Feathers",
    "Chants",
    "Sparkles",
    "Skies",
    "Stories",
    "Roads",
    "Keys",
    "Spades",
    "Diamonds",
    "Hearts",
    "Clubs",
    "Wisps",
    "Numbers",
    "Memories",
    "Wheels",
    "Strings",
    "Lands",
    "Eggs",
    "Hills",
    "Mountains",
    "Lakes",
    "Tiles",
    "Cords",
    "Knots",
    "Songs",
    "Nails",
    "Sheets",
    "Books",
    "Pages",
    "Knobs",
    "Voices",
    "Sparks",
    "Shores",
    "Tides",
    "Forms",
    "Motes",
    "Ladies",
    "Princesses",
    "Queens",
    "Empresses",
    "Duchesses",
    "Mistresses",
    "Lords",
    "Princes",
    "Kings",
    "Emperors",
    "Dukes",
    "Barons",
    "Masters",
  ],
  nounsOfIndeterminateQuantity: [
    "Jade",
    "Rain",
    "Dominion",
    "Leviathan",
    "Salvation",
    "Fate",
    "Change",
    "Sorrow",
    "Glass",
    "Crystal",
    "Heaven",
    "Sand",
    "Moonlight",
    "Dawn",
    "Dusk",
    "Mystery",
    "Magic",
    "Fire",
    "Ice",
    "Water",
    "Starlight",
    "Lightning",
    "Thunder",
    "Steel",
    "Glory",
    "Stone",
    "Bravery",
    "Poetry",
    "Promise",
    "Beauty",
    "Mirth",
    "Olympus",
    "Light",
    "Charity",
    "Mercy",
    "Hope",
    "Virtue",
    "Fortitude",
    "Enlightenment",
    "Might",
    "Destiny",
    "Grass",
    "Clarity",
    "Serenity",
    "Tranquility",
    "Paradise",
    "Contentment",
    "Strength",
    "Power",
    "Salt",
    "Atlantis",
    "Herring",
    "Doubt",
    "Flint",
    "Spring",
    "Summer",
    "Autumn",
    "Winter",
    "Snow",
    "Time",
    "Space",
    "Paper",
    "Rice",
    "Wheat",
    "Bread",
    "Cheddar",
    "Motion",
    "Ash",
    "Sagebrush",
    "Lead",
    "Tin",
    "Copper",
    "Bronze",
    "Brass",
    "Silver",
    "Gold",
    "Cloth",
    "Junk",
    "Logic",
    "Silence",
    "Wine",
    "Money",
    "Slate",
    "Graphite",
    "Cobalt",
    "Platinum",
    "Wood",
    "Ore",
    "Grain",
    "Fission",
    "Fusion",
    "Life",
    "Hair",
    "Smoke",
    "Essence",
    "Clay",
    "Myth",
    "Victory",
    "Defiance",
    "Borneo",
    "Grace",
  ],
  oneToTwelve: [
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "Eleven",
    "Twelve",
  ],
  pluralQuantities: [
    "Double",
    "Twin",
    "Two",
    "Three",
    "Triple",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "Eleven",
    "Twelve",
    "Thirteen",
    "Twenty",
    "Fifty",
    "One Hundred",
    "One Thousand",
    "Many",
    "So Many",
    "Too Many",
    "No More",
    "Several",
    "Numerous",
    "Infinite",
    "Enough",
    "All the",
  ],
  sometimesASuccessor: [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    " II",
    " III",
  ],

  standaloneCivilianShipNames: [
    "Horizon",
    "Enterprise",
    "Rabbit",
    "Napoleon",
    "Khagan",
    "Yokozuna",
    "Ozeki",
    "Black Bear",
    "Indefatigable",
    "Dauntless",
    "Nautilus",
    "Dolphin",
    "Humboldt",
    "Eagle",
    "Slipstream",
    "Stargazer",
    "Venture",
    "Union",
    "Sunrise",
    "Laotzu",
    "Mencius",
    "Hawk",
    "Confucius",
    "Megalith",
    "Istanbul",
    "Constantinople",
    "Winchester",
    "Magellan",
    "Constellation",
    "Orion",
    "Oracle",
    "Promised Land",
    "Garden of Eden",
    "George Washington",
    "Odysseus",
    "Poseidon",
    "Sinbad",
    "Falling Snow",
    "Quetzal",
    "Quetzlcoatl",
    "Icebreaker",
    "Gorgon",
    "Winston Churchill",
    "Saint Felix",
    "Orca",
    "Snowy Owl",
    "Bombay",
    "Arethusa",
    "Crown Point",
    "Botany Bay",
    "Medway",
    "Allure",
    "Bazinje",
    "Nomad",
    "Redoubtable",
    "Primarch",
    "Great Egret",
    "Jeanne d'Arc",
    "Geronimo",
    "Sitting Bull",
    "Pocahontas",
    "Crazy Horse",
    "Toreador",
    "Chelmsford",
    "Argo",
    "Golden Fleece",
    "Pequod",
    "Beagle",
    "Santa Maria",
    "Bismark",
    "Golden Hind",
    "Mayflower",
    "Monitor",
    "Merrimack",
    "Potemkin",
    "Yamato",
    "Fujiyama",
    "Pretoria",
    "Xiao Yi",
    "Lou Chuan",
    "Zheng He",
    "Baychimo",
    "Constitution",
    "Excelsior",
    "Renaissance",
    "Yellowstone",
    "Jim Jones",
    "John Henry",
    "Paul Bunyan",
    "Robin Hood",
    "Annie Oakley",
    "Emiliano Zapata",
    "North Star",
    "Wanderer",
    "Tears in Rain",
    "Happy Returns",
    "No Gods, No Masters",
    "Majestic",
    "Santa Fe",
    "Hunk of Junk",
    "Bucket of Bolts",
    "Slag Heap",
    "Flying Junkyard",
    "Hammerhead",
    "Heliopolis",
    "Cornwall",
    "Chichen Itza",
    "Small Potatoes",
    "Simon Bolivar",
    "Spartacus",
    "Harriet Tubman",
    "Stonewall Jackson",
    "Shaka Zulu",
    "Silk Road",
    "Good Egg",
    "Terrible Swift Sword",
    "Loaves and Fishes",
    "Hero of Old",
    "Ties That Bind",
    "A Quiet Truth",
    "Fantastic Planet",
    "Observer",
    "Times of Woe",
    "Henry Ford",
    "Charles de Gaulle",
    "Circe",
    "Amelia Earhart",
    "Charles Lindbergh",
    "Roald Dahl",
    "Larry the Ship",
    "Jim Bowie",
    "Pax Republica",
    "Riga",
    "Yerevan",
    "Brasilia",
    "Cape Town",
    "Borealis",
    "Narcissus",
    "Tea Clipper",
    "Close-Hauled",
    "Windjammer",
    "Windstar",
    "Potosi",
    "Minotaur",
    "Ouroboros",
    "Tiamat",
    "Artemis",
    "Annabel Lee",
    "Old Ironsides",
    "Spice of Life",
    "Purifying Gaze",
    "Chateau Gaillard",
    "Sacramento",
    "Labnathia",
    "Brick by Brick",
    "Murano",
    "Johannesburg",
    "Stapleton",
    "Righteous",
    "Venerable",
    "Mjolnir",
    "Starscreamer",
    "Barrabas",
    "Musashi",
    "Misaka",
    "Belo Horizonte",
    "Visby",
    "Pyotr Velikiy",
    "Invincible",
    "Renowned",
    "Courageous",
    "Indomitable",
    "Endurance",
    "Avenger",
    "Unrivaled",
    "Retribution",
    "Allegiance",
    "One Hand Clapping",
    "Washed Away",
    "Cash is King",
    "Equality",
    "Equanimity",
    "Eudamonia",
    "Independence",
    "Interdependence",
    "Mutuality",
    "Proteus",
    "William Rockefeller",
    "Lewis and Clark",
    "Leif Erikson",
    "Marco Polo",
    "Zheng He",
    "Vasco de Gama",
    "Amerigo Vespucci",
    "Jacques Cartier",
    "James Cook",
    "Horatio Hornblower",
    "Thorstein Veblen",
    "Karl Marx",
    "John Maynard Keynes",
    "Milton Friedman",
    "Missouri",
    "Montana",
    "Essex",
    "Karaboudjan",
    "Immer Essen",
    "Scotia",
    "Sherwood",
    "Thunderfish",
    "Venture",
    "Arabella",
    "Baalbek",
    "Barracuda",
    "Bellipotent",
    "Calypso",
    "Forrestal",
    "Compass Rose",
    "Covenant",
    "Dazzler",
    "Fenton",
    "Keeling",
    "Marie Celeste",
    "Hodgson",
    "Okinawa",
    "Orcus",
    "Pharaoh",
    "Pyramus",
    "Reluctant",
    "Saltash",
    "Sturgeon",
    "Swordfish",
    "Seaview",
    "Starview",
    "Umbriago",
    "Valparaiso",
    "Kandahar",
    "Colonia",
    "Shenandoah",
    "Destiny",
    "Rockingham",
    "Atropos",
    "Hotspur",
    "Speedwell",
    "Sutherland",
    "Magicienne",
    "Papillion",
    "Vestal",
    "Remembrance",
    "Ark",
    "Sardine",
    "Pinafore",
    "Minnow",
    "Skydiver",
    "Vondel",
    "Elisabeth Dane",
    "Valkyrie",
    "Geofon",
    "Beowulf",
    "Nunki",
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
    "Aquarius",
    "Pisces",
    "Aries",
    "Taurus",
    "Gemini",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Karkinos",
    "Krios",
    "Tavros",
    "Didimoi",
    "Leon",
    "Parthenos",
    "Zygos",
    "Skorpios",
    "Toksotis",
    "Aigokeros",
    "Ydrohoos",
    "Ihtheis",
    "Ophiuchus",
    "Saman Kunan",
    "Wat Phra Kaew",
    "Hakuho",
    "Tochinoshin",
    "Frida Kahlo",
    "Garcia Marquez",
    "Carrack",
    "Lizard",
    "Jack Tar",
    "Landsman",
    "Marlinspike",
    "Sultana",
    "Maidstone",
    "Gibraltar",
    "Donegal",
    "Preble",
    "Chesapeake",
    "Tripoli",
    "Mastico",
    "Syracuse",
    "Argus",
    "Syren",
    "Malaga",
    "Leopard",
    "Aeolus",
    "Africa",
    "Belvidera",
    "Guerriere",
    "Bonne Citoyenne",
    "Java",
    "Bainbridge",
    "Pictou",
    "Marblehead",
    "Cocteau",
    "Guinea",
    "Puna",
    "Turon",
    "Singapore",
    "Savannah",
    "Gambrill",
    "Cuyler",
    "Dewey",
    "Bodger",
    "Anzio",
    "Ardent",
    "Choson",
    "Coronado",
    "Berwick",
    "Firebolt",
    "Kersarge",
    "Laboon",
    "Manzanita",
    "Momsen",
    "Somerset",
    "Tortuga",
    "Colossus",
    "Benavidez",
    "Brittin",
    "Charlton",
    "Eagleview",
    "Guadalupe",
    "Alvaro de Bazan",
    "La Loba",
    "Swiftsure",
    "Laramie",
    "Pecos",
    "Taos",
    "Souverain",
    "Almaak",
    "Chakra",
    "Kalvari",
    "Shisumar",
    "Kolkata",
    "Rajput",
    "Vympel",
    "Shivalik",
    "Talwar",
    "Godavari",
    "Shardul",
    "Magar",
    "Kamorta",
    "Kora",
    "Khukri",
    "Abhay",
    "Saryu",
    "Sukanya",
    "Tinkat",
    "Shalki",
    "Chennai",
    "Mysore",
    "Ranvir",
    "Tabar",
    "Tarkash",
    "Galerna",
    "Mistral",
    "Castilla",
    "Lezo",
    "Serviola",
    "Canabrava",
    "Toralla",
    "Aresa",
    "Alboran",
    "Centinela",
    "Patino",
    "Elcano",
    "Toulon",
    "Richelieu",
    "Dunquerque",
    "Mers-el-Kebir",
    "Rubis",
    "Forbin",
    "Cassard",
    "Aquitaine",
    "Auvergne",
    "Blaison",
    "Belleisle",
    "Tonnant",
    "Bellerophon",
    "Mont Blanc",
    "Pluton",
    "Hortense",
    "Shohei Maru",
    "Asahi Maru",
    "Choyo",
    "Kaiten",
    "Mikaho",
    "Moshun",
    "Ryoju",
    "Kongo",
    "Tsukushi",
    "Katsuragi",
    "Akagi",
    "Kotetsu",
    "Fuso",
    "Yashima",
    "Mishima",
    "Okinoshima",
    "Satsuma",
    "Katori",
    "Kirishima",
    "Nagato",
    "Matsushima",
    "Yoshino",
    "Kasagi",
    "Takasago",
    "Chikuma",
    "Tenryu",
    "Kuma",
    "Sendai",
    "Soryu",
    "Izumo",
    "Hyuga",
    "Osumi",
    "Kunisaki",
    "Hatakaze",
    "Scheherazade",
    "Gormand",
    "Firstborn",
    "Adir",
    "Zumwalt",
    "Throckmorton",
    "Normandy",
    "Magna Carta",
    "Casablanca",
    "Message in a Bottle",
    "Monkey Business",
    "Dorngas",
    "Soyuz",
    "Gorshkov",
    "Zereguchniy",
    "Arthur Foss",
    "Chidiock Tichborne",
    "Vera Hugh",
    "Challenger",
    "Columbia",
    "Endeavor",
    "Discovery",
    "Babcock",
    "Wilcox",
    "Burke",
    "Fletcher",
    "Garfish",
    "Hornet",
    "Nitro",
    "Patoka",
    "Powhatan",
    "Salamonie",
    "Sassacus",
    "Yorktown",
    "Deep-Sea Baby",
    "Steady Progress",
    "Barnacle",
    "Humpback",
    "In the Reeds",
    "Northwest Passage",
    "Yuri Gagarin",
    "Buzz Aldrin",
    "Neil Armstrong",
    "Sally Ride",
  ],
  freeWorldsSmall: [
    "Lily",
    "Thistle",
    "Amaryllis",
    "Daisy",
    "Bell",
    "Bergamot",
    "Buttercup",
    "Chrysanthemum",
    "Banksia",
    "Carnation",
    "Aster",
    "Columbine",
    "Orchid",
    "Daffodil",
    "Primrose",
    "Cherry",
    "Foxglove",
    "Foxtail",
    "Gentian",
    "Ginger",
    "Gillyflower",
    "Amaranth",
    "Goldenrod",
    "Viburnum",
    "Hyacinth",
    "Larkspur",
    "Lavender",
    "Lilac",
    "Loosestrife",
    "Marigold",
    "Mimosa",
    "Mum",
    "Peony",
    "Rose",
    "Safflower",
    "Scarlet",
    "Slipper",
    "Snapdragon",
    "Berry",
    "Snowdrop",
    "Spurge",
    "Sedum",
    "Stonecrop",
    "Sunflower",
    "Tulip",
    "Yarrow",
    "Ambrosia",
    "Bittersweet",
    "Brier",
    "Clover",
    "Nettle",
    "Holly",
    "Ivy",
    "Morel",
    "Nightshade",
    "Poke",
    "Rye",
    "Saffron",
    "Sorrel",
    "Sage",
    "Rosemary",
    "Thyme",
    "Trillium",
    "Violet",
    "Purslane",
    "Vetch",
    "Burdock",
  ],
  republicSmall: [
    "Nile",
    "Amazon",
    "Mississippi",
    "Yangtze",
    "Zaire",
    "Mackenzie",
    "Niger",
    "Mekong",
    "Volga",
    "Madeira",
    "Yukon",
    "Rio",
    "Indus",
    "Danube",
    "Euphrates",
    "Darling",
    "Zambezi",
    "Murray",
    "Nelson",
    "Paraguay",
    "Ural",
    "Ganges",
    "Oxus",
    "Salween",
    "Arkansas",
    "Colorado",
    "Dnieper",
    "Allegheny",
    "Irawaddy",
    "Orange",
    "Orinoco",
    "Pilcomayo",
    "Columbia",
    "Don",
    "Sungari",
    "Saskatchewan",
    "Peace",
    "Tigris",
    "Breede",
    "Modder",
    "Ohlanga",
    "Palala",
    "Alph",
    "Onyx",
    "Amur",
    "Angara",
    "Dongjiang",
    "Pearl",
    "Daly",
    "Flinders",
    "Cooper",
    "Barwon",
    "Lachlan",
    "Macquarie",
    "Waikato",
    "Yarra",
    "Avon",
    "Boyne",
    "Clwyd",
    "Hayle",
    "Lagan",
    "Mersey",
    "Narva",
    "Rhine",
    "Severn",
    "Thames",
    "Tyne",
    "Hiwassee",
    "Loup",
    "Platte",
    "Potomac",
    "Schuylkill",
    "Susquehanna",
    "Wabash",
    "Sangamon",
    "Tsilma",
    "Vistula",
    "Tagus",
    "Loire",
    "Rhone",
    "Seine",
    "Tiber",
    "Devi",
    "Godavari",
    "Pitt",
    "Mohawk",
    "Athabasca",
    "Skagit",
    "Squamish",
    "Sanginaw",
    "Catatumbo",
    "Magdalena",
    "Jordan",
    "Liao",
    "Congo",
    "Senegal",
  ],
  asianPrefixes: [
    "Chan",
    "Chang",
    "Cheng",
    "Da",
    "Dai",
    "Dong",
    "Fu",
    "Guang",
    "Gui",
    "Hai",
    "Heng",
    "Hua",
    "Hou",
    "Huang",
    "Ji",
    "Jing",
    "Kai",
    "Ku",
    "Kun",
    "Kuo",
    "Lan",
    "Liao",
    "Liu",
    "Lo",
    "Lu",
    "Luo",
    "Man",
    "Nan",
    "Ning",
    "Pu",
    "Qi",
    "Ren",
    "Shan",
    "Shang",
    "Shen",
    "Sheng",
    "Tai",
    "Tian",
    "Uru",
    "Wang",
    "Wen",
    "Wo",
    "Wu",
    "Yan",
    "Yu",
    "Yuan",
    "Zheng",
    "Zhu",
    "Zi",
    "Zun",
  ],
  asian: [
    "Bei",
    "Bie",
    "Bo",
    "Chi",
    "Chun",
    "Chung",
    "Dao",
    "Ding",
    "Du",
    "Fan",
    "Fu",
    "Feng",
    "Gang",
    "Hai",
    "Han",
    "Hua",
    "Jin",
    "Kan",
    "Kou",
    "Lai",
    "Lan",
    "Lian",
    "Lin",
    "Men",
    "Ming",
    "Mu",
    "Ning",
    "Pan",
    "Sao",
    "Sha",
    "Shan",
    "Shu",
    "Tian",
    "Tie",
    "Ting",
    "Xia",
    "Xin",
    "Xing",
    "Yan",
    "Yang",
    "Ya",
    "Yi",
    "Yin",
    "Zang",
    "Ze",
    "Zhao",
    "Zheng",
    "Zhou",
    "Zhuang",
  ],
  asianSuffixes: [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    " II",
    " III",
    " Hu",
    " Shan",
    " Tang",
    " Chuan",
    " Shun",
    " Gang",
  ],
  prefixes: [
    "Star",
    "Sun",
    "Moon",
    "Sky",
    "Sea",
    "Space",
    "Cloud",
    "Wave",
    "Wind",
    "Void",
    "Fire",
    "Flame",
    "Ice",
    "Snow",
    "Storm",
    "Swift",
    "Rose",
    "Time",
    "Smoke",
    "Steam",
    "Night",
    "Rain",
  ],
  suffixes: [
    " King",
    " Queen",
    " Ace",
    "gazer",
    "stream",
    "streak",
    "light",
    "born",
    "baby",
    "bolt",
    "flare",
    "burst",
    "bright",
    "boy",
    "girl",
    "rider",
    "lover",
    "racer",
    "jumper",
    "seeker",
    "sought",
    "swept",
    "piercer",
    "chaser",
    "hunter",
    "beater",
    "charger",
    "speeder",
    "runner",
    "spear",
    "sword",
    "surfer",
    "strider",
    "dreamer",
    "stinger",
    "lord",
    "lady",
    "wise",
    "joy",
    "talker",
    "walker",
    "step",
    "bringer",
    "caller",
    "bite",
    "spinner",
    "weaver",
    "wisp",
    "warrior",
    "hero",
    "gust",
    "banner",
    "bug",
    "swan",
    "comet",
    "gem",
    "dream",
    "ghost",
    "tongue",
    "hawk",
    "ship",
    "hand",
    "shadow",
    "breather",
    "wing",
    "lace",
    "bark",
    "honey",
    "-Crossed",
    "well",
    "worn",
  ],
  republicCapital: [
    "Everest",
    "Kilimanjaro",
    "Massif",
    "McKinley",
    "Aconcagua",
    "Denali",
    "Kenya",
    "Logan",
    "Cathkin",
    "Elgon",
    "Sinai",
    "Erebus",
    "Kirkpatrick",
    "Markham",
    "McClintock",
    "McMaster",
    "Annapurna",
    "Kamet",
    "Lhotse",
    "Makalu",
    "Shivling",
    "Kangri",
    "Laila",
    "Mitre",
    "Ultar",
    "Jade",
    "Fuji",
    "Korbu",
    "Victoria",
    "Ararat",
    "Hermon",
    "Hebron",
    "Breithorn",
    "Eiger",
    "Paradiso",
    "Olympus",
    "Matterhorn",
    "Nordend",
    "Weisshorn",
    "Etna",
    "Parnassus",
    "Vesuvius",
    "Telemark",
    "Oppland",
    "Snowdon",
    "Scafell",
    "Vancouver",
    "Hubbard",
    "Walsh",
    "Augusta",
    "Strickland",
    "Cook",
    "Columbia",
    "Wood",
    "Douglas",
    "Hector",
    "Razorback",
    "Raleigh",
    "Blackcomb",
    "Thor",
    "Sierra",
    "Adams",
    "Baker",
    "Baxter",
    "Clark",
    "Cleveland",
    "Evans",
    "Foraker",
    "Gannett",
    "Greylock",
    "Helen",
    "Hood",
    "Jackson",
    "Monadnock",
    "Rainier",
    "Sacagawea",
    "Tabor",
    "Washington",
    "Haleakala",
    "Nanshan",
    "Manaslu",
    "Trivor",
    "Rimo",
    "Chongtar",
    "Karjiang",
    "Kibo",
    "Guna",
    "Sidley",
    "Foster",
    "Haddington",
    "Brewster",
    "Albaron",
    "Sabinio",
    "Koussi",
    "Brandberg",
    "Lengai",
    "Elgon",
    "Vinson",
    "Tai",
    "Wutai",
    "Kangto",
    "Toba",
    "Jaya",
    "Krakatoa",
    "Ossa",
    "Blanc",
    "Pelion",
    "Toluca",
    "Kilauea",
    "Mondanock",
    "Rushmore",
    "Shasta",
    "Taranaki",
    "Huascaran",
    "Sandia",
  ],
  deep: [
    "Aristotle",
    "Aristarchus",
    "Archimedes",
    "Avogadro",
    "Abbe",
    "Alcubierre",
    "Abbott",
    "Alvarez",
    "Angstrom",
    "Anderson",
    "Bell",
    "Becquerel",
    "Bernoulli",
    "Bohr",
    "Brahe",
    "Cherenkov",
    "Coriolis",
    "Coulomb",
    "Curie",
    "Dalton",
    "Democritus",
    "Dewar",
    "Dirac",
    "Doppler",
    "Einstein",
    "Englert",
    "Euler",
    "Edison",
    "Fahrenheit",
    "Faraday",
    "Fermi",
    "Feynman",
    "Fourier",
    "Franklin",
    "Fresnel",
    "Galvani",
    "Geiger",
    "Hall",
    "Hawking",
    "Heisenberg",
    "Hertz",
    "Higgs",
    "Hooke",
    "Hubble",
    "Huygens",
    "Joule",
    "Kepler",
    "Lagrange",
    "Lebedev",
    "Leibniz",
    "Lyapunov",
    "Mach",
    "Marconi",
    "Maxwell",
    "Neumann",
    "Newcomb",
    "Newton",
    "Ohm",
    "Oppenheimer",
    "Pascal",
    "Penrose",
    "Planck",
    "Poincare",
    "Poisson",
    "Rayleigh",
    "Richter",
    "Roentgen",
    "Sagan",
    "Schroedinger",
    "Schwarzschild",
    "Tesla",
    "Watson",
    "Watt",
    "Weber",
  ],
  militia: [
    "Terebinth",
    "Tamarack",
    "Juniper",
    "Maple",
    "Willow",
    "Cedar",
    "Ponderosa",
    "Douglas",
    "Elm",
    "Cork",
    "Hemlock",
    "Larch",
    "Sequoia",
    "Redwood",
    "Ginko",
    "Dogwood",
    "Bartlett",
    "Magnolia",
    "Baobab",
    "Banyan",
    "Cypress",
    "Teak",
    "Hawthorn",
    "Hophorn",
    "Poplar",
    "Sycamore",
    "Aspen",
    "Holly",
    "Ebony",
    "Birch",
    "Borage",
    "Asphodel",
    "Heath",
    "Beech",
    "Laurel",
    "Myrtle",
    "Buckthorn",
    "Nightshade",
    "Tamarisk",
    "Pinyon",
    "Eucalyptus",
    "Joshua",
    "Yucca",
    "Torrey",
    "Sumac",
    "Aloe",
    "Alder",
    "Hazel",
    "Ironwood",
    "Elder",
    "Mangrove",
    "Persimmon",
    "Crabwood",
    "Tallow",
    "Winterthorn",
    "Senna",
    "Carob",
    "Redbud",
    "Coral",
    "Locust",
    "Hickory",
    "Lancewood",
    "Sassafras",
    "Primrose",
    "Brisbane",
    "Ash",
    "Privet",
    "Raywood",
    "Quince",
    "Medlar",
    "Balsam",
    "Traveler",
    "Spurge",
    "Linden",
    "Cottonwood",
    "Kapok",
    "Mesquite",
    "Spruce",
    "Chestnut",
    "Chinquapin",
    "Walnut",
  ],
  freeWorldsCapital: [
    "Terebinth",
    "Tamarack",
    "Juniper",
    "Maple",
    "Willow",
    "Cedar",
    "Ponderosa",
    "Douglas",
    "Elm",
    "Cork",
    "Hemlock",
    "Larch",
    "Sequoia",
    "Redwood",
    "Ginko",
    "Dogwood",
    "Bartlett",
    "Magnolia",
    "Baobab",
    "Banyan",
    "Cypress",
    "Teak",
    "Hawthorn",
    "Hophorn",
    "Poplar",
    "Sycamore",
    "Aspen",
    "Holly",
    "Ebony",
    "Birch",
    "Borage",
    "Asphodel",
    "Heath",
    "Beech",
    "Laurel",
    "Myrtle",
    "Buckthorn",
    "Nightshade",
    "Tamarisk",
    "Pinyon",
    "Eucalyptus",
    "Joshua",
    "Yucca",
    "Torrey",
    "Sumac",
    "Aloe",
    "Alder",
    "Hazel",
    "Ironwood",
    "Elder",
    "Mangrove",
    "Persimmon",
    "Crabwood",
    "Tallow",
    "Winterthorn",
    "Senna",
    "Carob",
    "Redbud",
    "Coral",
    "Locust",
    "Hickory",
    "Lancewood",
    "Sassafras",
    "Primrose",
    "Brisbane",
    "Ash",
    "Privet",
    "Raywood",
    "Quince",
    "Medlar",
    "Balsam",
    "Traveler",
    "Spurge",
    "Linden",
    "Cottonwood",
    "Kapok",
    "Mesquite",
    "Spruce",
    "Chestnut",
    "Chinquapin",
    "Walnut",
  ],
  syndicateCapital: [
    "Africanus",
    "Agrippa",
    "Varus",
    "Antonius",
    "Diogenes",
    "Aquila",
    "Atticus",
    "Augustus",
    "Aurelius",
    "Brutus",
    "Caesar",
    "Julius",
    "Calpurnia",
    "Cassius",
    "Catilina",
    "Cato",
    "Catullus",
    "Cicero",
    "Cincinnatus",
    "Claudius",
    "Clemens",
    "Commodus",
    "Coriolanus",
    "Metella",
    "Crassus",
    "Diocletian",
    "Domitian",
    "Fabius",
    "Felix",
    "Festus",
    "Flaccus",
    "Horace",
    "Caligula",
    "Gracchus",
    "Hadrian",
    "Lucretia",
    "Lucretius",
    "Licinius",
    "Metellus",
    "Milo",
    "Nero",
    "Nerva",
    "Flavian",
    "Ovid",
    "Paullus",
    "Petronius",
    "Piso",
    "Placidus",
    "Plautus",
    "Pliny",
    "Trajan",
    "Plutarch",
    "Pompeius",
    "Pompilius",
    "Porcia",
    "Porsenna",
    "Remus",
    "Romulus",
    "Roscius",
    "Rufus",
    "Sabinus",
    "Sallust",
    "Octavian",
    "Scaevola",
    "Scipio",
    "Severus",
    "Suetonius",
    "Sulla",
    "Tacitus",
    "Tarquin",
    "Tiberius",
    "Trajan",
    "Valerian",
    "Varus",
    "Vespasian",
    "Virgil",
  ],
  color: ["Red", "Orange", "Green", "Yellow", "Blue", "Gold"],
  greek: ["Alpha", "Beta", "Delta", "Gamma", "Epsilon"],
  animal: ["Wolf", "Hound", "Fox"],
  phonetic: [
    "Bravo",
    "Charlie",
    "Echo",
    "Foxtrot",
    "Golf",
    "Hotel",
    "India",
    "Juliet",
    "Kilo",
    "Lima",
    "Mike",
    "November",
    "Oscar",
    "Papa",
    "Quebec",
    "Romeo",
    "Sierra",
    "Tango",
    "Uniform",
    "Victor",
    "Whiskey",
    "X-Ray",
    "Yankee",
    "Zul ",
  ],
  // Pirate Stuff
  sinisterNames: [
    "Blackbeard",
    "Bluebeard",
    "Lilith",
    "Horus",
    "Baal",
    "Chernabog",
    "Abaddon",
    "Satan",
    "Mordecai",
    "Jezebel",
    "Pandora",
    "Asmodan",
    "Charon",
    "Mordred",
    "Baphomet",
    "Haekati",
    "Deava",
    "Amon",
    "Gehenna",
    "Malik",
    "Perdition",
    "Nergal",
    "Azazel",
    "Lucifer",
    "Vexan",
    "Babi",
    "Belial",
    "Djinn",
    "Nosferatu",
    "Ravenna",
    "Simon",
    "Tarik",
    "Agrona",
    "Lorelei",
    "Cassandra",
    "Balthazar",
    "Rasputin",
    "Khan",
    "Malachai",
    "Bart",
    "Draco",
    "Gozer",
    "Secor",
    "Cain",
    "Judas",
    "Herod",
    "Medusa",
    "Gorkon",
    "Naxo",
    "Abigor",
    "Seth",
    "Apep",
    "Ahriman",
    "Morfran",
    "Zagan",
    "Mara",
    "Koklir",
    "Dracula",
    "Usha",
    "Grendel",
    "Narkan",
    "Vulkan",
    "Chaxo",
    "Garzad",
    "Ivan",
    "Vlad",
    "Gord",
    "Urgok",
    "Bruja",
    "Dante",
  ],
  pirateAdjectivesThatWorkAsTitles: [
    "Bad",
    "Red",
    "Crimson",
    "Grey",
    "Black",
    "Dark",
    "Dead",
    "Blackguard",
    "Ghoulish",
    "Dreadful",
    "Baleful",
    "Venomous",
    "Lost",
    // "Damned",
    "Darned",
    "Fallen",
    "Brutal",
    "Blinded",
    "Savage",
    "Bloody",
    "Terrible",
    "Horrible",
    "Evil",
    "Wicked",
    "Trickster",
    "Deadly",
    "Rotten",
    "Tattered",
    "Rusty",
    "Painful",
    "Murderous",
    "Sadistic",
    "Flayed",
    "Greedy",
    "Violent",
    "Furious",
    "Hideous",
    "Profane",
    "Cold",
    "Mad",
    "Cannibal",
    "Manic",
    "Salty",
    "Greasy",
    "Nasty",
    "Impaler",
    "Grotesque",
    "Hateful",
    "Grim",
    "Fat",
    "Portly",
  ],
  pirateAdjectivesThatDontWorkAsTitles: [
    "Sea",
    "Morning",
    "Night",
    "Evening",
    "Midnight",
    "Golden",
    "Silver",
    "Flying",
    "Sky",
    "Sunset",
    "Shadow",
    "Thunder",
    "Poisoned",
    "Towering",
    "Sundered",
    "Chaos",
    "Boiling",
    "Shackled",
    "Bleeding",
    "Scorched",
    "Moonlight",
    "Devouring",
    "Ruinous",
    "Ruined",
    "Nightmare",
    "Screaming",
    "Suffocating",
    "Laughing",
    "Crumbling",
    "Crippled",
    "Despairing",
    "Uncontrollable",
    "Infernal",
    "Creaking",
    "Leaking",
    "Stained",
    "Slaughtered",
    //"Hellish",
    "Hecking",
    "Slavering",
    "Ravening",
    "Rabid",
    "Wounded",
    "Naked",
    "Hobbled",
    "Chained",
    "Haunted",
    "Piercing",
    "Thunderous",
    "Unending",
    "Endless",
    "Overwhelming",
    "Sinking",
    "Stinking",
    "Simmering",
    "Jagged",
    "Silenced",
    "Cancerous",
    "Severed",
    "Boiled",
    "Swift",
    "Naughty",
    "Woeful",
    "Silent",
    "Churning",
    "Blackened",
    "Splattered",
  ],
  pirateAdjectivesThatDontWorkBeforeSingularNouns: [
    "Flames of",
    "Reign of",
    "Death by",
    "Screams of",
    "Cackles of",
    "Wrath of",
    "Fist of",
    "Hall of",
    "Pit of",
    "Teeth of",
    "Abyss of",
    "Chains of",
    "Coils of",
    "Fits of",
    "House of",
  ],
  pirateNouns: [
    "Star",
    "Spectre",
    "Queen",
    "Wolf",
    "Rover",
    "Rambler",
    "Prince",
    "Princess",
    "Dragon",
    "Hunter",
    "Killer",
    "Bandit",
    "Thief",
    "Chain",
    "Falcon",
    "Raptor",
    "Hawk",
    "Stag",
    "Fog",
    "Marauder",
    "Dominator",
    "Sword",
    "Knife",
    "Cutlass",
    "Cannon",
    "Slaughter",
    "Inferno",
    "Abyss",
    "Tyrant",
    "Usurper",
    "Ravager",
    "Massacre",
    "Exile",
    "Storm",
    "Intruder",
    "Naga",
    "Dungeon",
    "Hook",
    "Tattoo",
    "Horns",
    "Slash",
    "Morningstar",
    "Serpent",
    "Hammer",
    "Children",
    "Thunderbolt",
    "Tomb",
    "Barrel",
    "Tankard",
    "Bolt",
    "Brig",
    "Realm",
    "Hands",
    "Fate",
    "Raider",
    "Revenge",
    "Anger",
    "Axe",
    "Dagger",
    "Skull",
    "Plague",
    "Ghost",
    "Rum",
    "Snakes",
    "Abbatoir",
    "Asylum",
    "Sausage",
    "Striker",
    "Sorcerer",
    "Banshee",
    "Siren",
    "Corpse",
    "Butcher",
    "Mother",
    "Eidolon",
    "Lashes",
    "Brute",
    "Reaper",
    "Witch",
    "Wench",
    "Tide",
    "Vandal",
    "Grog",
    "Shanker",
    "Stabber",
    "Maniac",
    "Lunatic",
    "Eye",
    "Grave",
    "Tar",
    "Lies",
    "Razor",
    "Lady",
    "Maiden",
    "Shards",
    "Mess",
    "Skag",
    "Bomber",
    "Conqueror",
    "Soul",
    "Head",
    "Face",
    "Dirge",
    "Stalker",
    "Heart",
    "Slayer",
    "Vulture",
  ],
  badPirateNouns: [
    "Ship",
    "Barge",
    "Hulk",
    "Galley",
    "Lugger",
    "Pit",
    "Tower",
    "Fortress",
    "Chamber",
    "Prison",
    "Monster",
    "Beast",
    "Demon",
    "Ogre",
    "Corsair",
    "Volcano",
    "King",
    "Blade",
    "Bell",
    "Omen",
    "Trap",
    "Ritual",
    "Devil",
    "God",
    "Hydra",
    "Blade",
    "Army",
  ],
  badOutcomes: [
    "Doom",
    "Death",
    "Ruin",
    "Pain",
    "Agony",
    "Decay",
    "Screams",
    "Torment",
    "Torture",
    "Madness",
    "Insanity",
    "Misery",
    "Anguish",
    "Conquest",
    "Domination",
    "Darkness",
    "Spite",
    "Violation",
    "Apocalypse",
    "Nightmare",
    "Ragnarok",
    // "Hell",
    "Heck",
    "Plunder",
    "Malice",
    "Destruction",
    "Blood",
    "Poison",
    "Blight",
    "Fury",
    "Misfortune",
    // "Damnation",
    "Tarnation",
    "Contagion",
    "Betrayal",
    "Hatred",
    "Vileness",
    "Murder",
    "Oppression",
    "Panic",
    "Might",
    "Woe",
    "Fury",
    "Rage",
    "Grief",
    "Addiction",
    "Slavery",
    "Mischief",
    "Cataclysm",
    "Immolation",
    "Wrath",
    "Blackness",
  ],
  pirateNames: [
    "Caleuche",
    "Lady Lovibond",
    "Flying Dutchman",
    "Princess Augusta",
    "Eliza Battle",
    "Iron Mountain",
    "Eurydice",
    "Valencia",
    "Octavius",
    "Red Jenny",
    "Ourang Medan",
    "Sea Bird",
    "Resolute",
    "Mary Celeste",
    "Resolven",
    "Zebrina",
    "Deering",
    "Bavchimo",
    "Governor Parr",
    "Joyita",
    "Teignmouth Electron",
    "Ocean Wave",
    "High Aim",
    "Jian Seng",
    "Bel Amica",
    "Kaz II",
    "Tai Ching",
    "Lunatic",
    "Ryou-Un Maru",
    "T. T. Zion",
    "Lyubov Orlova",
    "Skeleton Key",
    "Ampoliros",
    "Demeter",
    "William Kidd",
    "Adventure Gallery",
    "Adventure Prize",
    "Blackbeard",
    "Queen Anne's Revenge",
    "Adventure",
    "Good Fortune",
    "Scowerer",
    "Wyndham Galley",
    "Speakwell",
    "Sultana",
    "Whydah",
    "Ranger",
    "Lark",
    "Flying Dragon",
    "Golden Fleece",
    "Trompeuse",
    "La Nouvelle Trompeuse",
    "Sea Nymph",
    "Rising Sun",
    "Postillion",
    "Indian Queen",
    "Marianne",
    "Revenge",
    "Happy Return",
    "Night Rambler",
    "Flying King",
    "Delight",
    "Amity",
    "Liberty",
    "Royal James",
    "Fancy Dutch",
    "Pembroke",
    "Margaret",
    "Prosperous",
    "Rose Pink",
    "Squirrel",
    "Merry Christmas",
    "Happy Birthday",
    "Roebuck",
    "Katherine",
    "Defiance",
    "Rover",
    "Diamond Grey",
    "Barsheba",
    "St. Marie",
    "Grey Wolf",
    "Sea Wolf",
    "Morning Star",
    "Antelope",
    "Dead Dog",
    "Jolly Roger",
    "In the Flesh",
    "Cheeki Breeki",
    "Styx",
    "Attila the Hun",
    "Edward Teach",
    "Anne Bonny",
    "Calico Jack",
    "Jeanne de Clisson",
    "Lo Hon-cho",
    "Hyperion",
    "Samuel Axe",
    "Vlad the Impaler",
    "Elizabeth Bathory",
    "Morgan le Fay",
    "Charnel Ground",
    "Gaping Wound",
    "Festering Wounds",
    "Horrible Flies",
    "Death's Head",
    "Throne of Skulls",
    "Jack the Ripper",
    "Baba Yaga",
    "Bony Fingers",
    "Yo Ho Ho",
    "Low Blow",
    "Bilgewater",
    "Betrayer",
    "Hangman's Noose",
    "Unspeakable Acts",
    "Vampire",
    "Werewolf",
    "Billy the Kid",
    "Al Capone",
    "Gorkon Death Sloop",
    "Zokk Death Sloop",
    "Cold Winter",
    "Stilled Voices",
    "Cacophony",
    // "Into the Maw of Hell",
    "Into the Maw of Heck",
    "Slag Heap",
    "Golden Calf",
    "Crown of Thorns",
    "Torquemada",
    "Death Stare",
    "Mushroom Cloud",
    "La Llorona",
    "Eaten Alive",
    "Flayed Alive",
    "Burned Alive",
    "Boiled Alive",
    "Buried Alive",
    "Mongol Hordes",
    "Death Blow",
    "Death's Head",
    "Black Hand",
    "Malefactor",
    "Bell of Souls",
    "Despair",
    "Dreadful",
    "Garbage Day",
    "Heart of Darkness",
    "Lamentation",
    "Havoc",
    "Unspeakable",
    "Conqueror",
    "Punishment",
    "Naglfar",
    "Gorfival",
    "Tarnation",
    "Bewitched",
    "In Tatters",
    "Davy Jones' Locker",
    "Cement Shoes",
    "Chained to an Oar",
    "Bloody Mary",
    "Cat o' Nine Tails",
    "Man o' War",
    "Death Roll",
    "Dreadnought",
    "Blighter",
    "Polyphemus",
    "Needleroozer",
    "Furioso",
    "Terrifying",
    "Asphyxiation",
    "Drowning in Blood",
    "Pulled Apart",
    "Sleepless Nights",
    "Cancer",
    "Virago",
    "Necros",
    "So Much Blood",
    "Roast Baby",
    "Stiletto",
    "Rapier",
    "Kukri",
    "Executioner",
    "Torturer",
    "Evil Intent",
    "Dead Man's Chest",
    "Broken Wing",
    "Barge of the Dead",
    "Nuclear Winter",
    "Terminus Est",
    "Shipworm",
    "Lamprey",
    "Black Spot",
    "Retiarius",
    "Murmillo",
    "Secutor",
    "Samnite",
    "Glatiatrix",
    "Keelhauled",
    "Danegeld",
    "Terror",
  ],
  piratePrefixes: [
    "Blood",
    "Night",
    "Death",
    "Dead",
    "Doom",
    "Dark",
    "Hate",
    "Mad",
    "Mind",
    "Gut",
    "Grim",
    "Dread",
    "Bone",
    "Brain",
    "Chain",
    "Foul",
    "Evil",
    "Black",
    "Red",
    "Pain",
    "War",
    "Horn",
    "Murder",
    "Poison",
    "Scream",
    "Kill",
    "Spear",
    "Worm",
    "Power",
    "Shock",
    "Gore",
    "Woe",
    "Storm",
    "Hard",
    //"Hell",
    "Heck",
    "Filth",
  ],
  pirateSuffixes: [
    "oath",
    "fire",
    "spit",
    "fury",
    "rot",
    "bat",
    "bath",
    "blade",
    "flame",
    "curse",
    "scowl",
    "wrench",
    "wrought",
    "corpse",
    "fear",
    "stain",
    "sludge",
    "hunter",
    "shark",
    "-eater",
    "cradle",
    "pulse",
    "fang",
    "claw",
    "grave",
    "hammer",
    "river",
    "pit",
    "scourge",
    "plague",
    "storm",
    "rage",
    "slag",
    "fist",
    "punch",
    "slash",
    "chop",
    "wreck",
    "stab",
    "beast",
    "monger",
    "monster",
    "slayer",
    "snake",
    "rat",
    "sport",
    "shard",
    "spike",
    "stump",
    "snap",
    "frag",
    "bringer",
    "flicker",
    "boil",
    "rider",
    "raider",
    "stalker",
    "swarm",
    "fiend",
    "mouth",
    "face",
    "lord",
    "finger",
    "sliver",
    "splinter",
    "splitter",
    "snapper",
    "flinger",
    "breaker",
    "blaster",
    "slave",
    "sucker",
    "horse",
    "tooth",
    "stench",
    "gard",
    "hand",
    "shot",
    "-eye",
    "dog",
    "cat",
    "head",
    "star",
    "fink",
    "spot",
  ],
  pirateTitles: [
    "No",
    "No More",
    "Lost",
    "Forgotten",
    "Stolen",
    "End of",
    "Dead",
    "Hopeless",
    //"Hell's",
    "Heck's",
    "Angry",
    "Burning",
    "Infernal",
    "Rotted",
    "Psychotic",
    "Psycho",
    "Evil",
    "Bad",
    "Toxic",
    "Punctured",
    "Fractured",
    "Sundered",
    "Broken",
    "Vanquished",
    "Drowned",
  ],
  pirateHonorifics: [
    "Love",
    "Masters",
    "Hope",
    "Fate",
    "Mercy",
    "Laughter",
    "Innocence",
    "Children",
    "Freedom",
    "Liberty",
    "Happiness",
    "Honor",
    "Pride",
    "Dignity",
    "Life",
    "Breath",
    "Beauty",
    "Angels",
    "Music",
    "Glory",
    "Victory",
    "Mother",
    "Childhood",
    "Triumph",
    "Time",
    "Fate",
    "Boys",
  ],
  bountyHunterPrefixes1: [
    "Iron",
    "Brass",
    "Sharpened",
    "Green",
    "Grey",
    "Black",
    "Dark",
    "Obsidian",
    "Studded",
    "Marked",
    "Plated",
    "Mailed",
    "Moonlit",
    "Cursed",
    "Silvered",
    "Tempered",
    "Relentless",
    "Fated",
    "Dogged",
    "Tireless",
    "Fanged",
    "Vampire",
    "Zealous",
    "Holy",
    "Chosen",
    "Harsh",
  ],
  bountyHunterSuffixes1: [
    "Kingdom",
    "Tyrant",
    "Blades",
    "Spear",
    "Lance",
    "Sword",
    "Shield",
    "Glaive",
    "Mace",
    "Whip",
    "Flail",
    "Slave",
    "Talisman",
    "Torch",
    "Fist",
    "Steed",
    "Crag",
    "Ravine",
    "Cliff",
    "Prison",
    "Cage",
    "Shackle",
    "Knight",
    "Crusader",
    "Inquisitor",
    "Templar",
    "Protector",
    "Hunter",
    "Hunt",
    "Judge",
    "Justice",
    "Hound",
    "Warhorse",
    "Lion",
    "Vindicator",
    "Punisher",
    "Nemesis",
    "Fury",
    "Rivets",
  ],
  bountyHunterPrefixes2: [
    "Bars",
    "Chains",
    "Spires",
    "Tower",
    "Bastion",
    "Fortress",
    "Pit",
    "Helm",
    "Fist",
    "Sloop",
    "Drums",
    "Golem",
    "Cask",
    "Spikes",
    "Tongs",
    "Prison",
    "Dungeon",
    "Maze",
    "Cauldron",
    "Guns",
    "Cannons",
    "Tome",
    "Staff",
    "Sword",
    "Scepter",
    "Vision",
    "Grasp",
  ],
  bountyHunterSuffixes2: [
    "Rust",
    "Steel",
    "Rock",
    "Clay",
    "Iron",
    "Oak",
    "Misery",
    "Stone",
    "Ruin",
    "War",
    "Night",
    "Man",
    "Law",
    "Order",
    "Justice",
    "Fate",
    "Despair",
    "the Lost",
    "Punishment",
    "St. Dunstan",
    "Gilgamesh",
    "Boudicca",
    "Prometheus",
    "Sisyphus",
    "Tantalus",
    "Hector",
    "Rome",
  ],
  quargPrefixes: [
    "Quar",
    "Mer",
    "Ban",
    "Koor",
    "Plog",
    "Flum",
    "Krak",
    "Grok",
    "Merak",
  ],
  quargInterstitials: [
    "-",
    "ala",
    "gor",
    "o",
    "i",
    "oni",
    "lam",
    "tim",
    "ee",
    "shee",
  ],
  quargSuffixes: [
    "lim",
    "kor",
    "far",
    "mor",
    "lup",
    "plug",
    "trum",
    "ruk",
    "rook",
  ],
  pugPrefixes: [
    "Pak",
    "Mug",
    "Prot",
    "Dor",
    "Mek",
    "Cam",
    "Yot",
    "Quim",
    "Tsoop",
    "Froid",
    "Groip",
    "Ploort",
    "Schmar",
    "Klar",
    "Brek",
  ],
  pugInterstitials: [
    " ",
    " Kim ",
    " Wor ",
    " Moof ",
    " Plat ",
    " Del ",
    " Ben ",
    " Gred ",
    " Klort ",
    " Rep ",
    " For ",
    " a ",
    " io ",
    " el ",
    " ",
    " ",
  ],
  pugSuffixes: [
    "Glorf",
    "Florp",
    "Marg",
    "Graw",
    "Ged",
    "Peg",
    "Plog",
    "Hort",
    "Noor",
    "Joop",
    "Drap",
    "Loit",
    "Sol",
    "Wan",
  ],
  theNouns() {
    return duplicateList(this.singularNouns, 4)
      .concat(this.cardinalDirections)
      .concat(this.nounsOfIndeterminateQuantity)
      .map(w => `the ${w}`);
  },
  thingsYouCanBeOf() {
    return this.pluralNouns.concat(this.theNouns()).map(w => `of ${w}`);
  },
  allTitles() {
    return this.maleTitles
      .concat(this.femaleTitles)
      .concat(this.genderNeutralTitles);
  },
};
