import type { Range } from "@thorium/utils/operations/randomFromRange";
import z from "zod";

import type { Kelvin, Kilometer, TerranMass, Year } from "../unitTypes";

export const planetClasses = z.union([
	z.literal("A"),
	z.literal("B"),
	z.literal("C"),
	z.literal("D"),
	z.literal("E"),
	z.literal("F"),
	z.literal("G"),
	z.literal("H"),
	z.literal("I"),
	z.literal("J"),
	z.literal("K"),
	z.literal("L"),
	z.literal("M"),
	z.literal("N"),
	z.literal("O"),
	z.literal("P"),
	z.literal("S"),
]);
export type PlanetClasses = z.infer<typeof planetClasses>;
export type Zone = ("hot" | "cold" | "habitable")[];
export const atmosphericComposition = z
	.object({ component: z.string(), concentration: z.number() })
	.array();
export type AtmosphericComposition = z.infer<typeof atmosphericComposition>;

const possibleRingMaps = [
	"/plugins/Thorium Default/assets/rings/rings1.png",
	"/plugins/Thorium Default/assets/rings/rings2.png",
	"/plugins/Thorium Default/assets/rings/rings3.png",
	"/plugins/Thorium Default/assets/rings/rings4.png",
	"/plugins/Thorium Default/assets/rings/ring_texturesDust.png",
	"/plugins/Thorium Default/assets/rings/ring_texturesSmall.png",
	"/plugins/Thorium Default/assets/rings/ring_texturesClouds.png",
	"/plugins/Thorium Default/assets/rings/ring_texturesSharp.png",
	"/plugins/Thorium Default/assets/rings/ring_texturesRocks.png",
];

interface PlanetType {
	name: string;
	canBeMoon?: boolean;
	classification: PlanetClasses;
	temperatureRange: Range<Kelvin>;
	zone: Zone;
	radiusRange: Range<Kilometer>;
	ageRange: Range<Year>;
	terranMassRange: Range<TerranMass>;
	population: number | Range<number>;
	atmosphericComposition: AtmosphericComposition;
	habitable: boolean;
	lifeforms: string[];

	possibleTextureMaps: string[];

	hasRings: number;
	possibleRingMaps: string[];

	hasClouds: number;
	possibleCloudMaps: string[];
}

export const planetTypes: PlanetType[] = [
	{
		classification: "A",
		name: "Geothermal",
		canBeMoon: true,
		ageRange: { min: 1000000, max: 2000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None"],
		population: 0,
		radiusRange: { min: 500, max: 5000 },
		zone: ["habitable", "cold"],
		temperatureRange: { min: 1383, max: 1783 },
		terranMassRange: { min: 0.1, max: 1.2 },
		hasClouds: 0,
		hasRings: 0,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/planet_textureAuric.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureAcid.jpg",
			"/plugins/Thorium Default/assets/planets/mercurymap.jpg",
		],
		possibleCloudMaps: [],
		possibleRingMaps,
	},
	{
		classification: "B",
		name: "Geomorteus",
		canBeMoon: true,
		ageRange: { min: 1000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None"],
		population: 0,
		radiusRange: { min: 500, max: 5000 },
		zone: ["hot"],
		temperatureRange: { min: 90, max: 740 },
		terranMassRange: { min: 0.1, max: 1.2 },
		hasClouds: 0,
		hasRings: 0,

		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/2k_mercury.jpg",
			"/plugins/Thorium Default/assets/planets/plutomap1k.jpg",
		],
		possibleCloudMaps: [],
		possibleRingMaps,
	},
	{
		classification: "C",
		name: "Geoinactive",
		canBeMoon: true,
		ageRange: { min: 20000000, max: 1000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None"],
		population: 0,
		radiusRange: { min: 500, max: 5000 },
		zone: ["habitable", "cold"],
		temperatureRange: { min: 33, max: 55 },
		terranMassRange: { min: 0.1, max: 1 },
		hasClouds: 0,
		hasRings: 0,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/planet_textureDust.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureAzure.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg",
		],
		possibleCloudMaps: [],
		possibleRingMaps,
	},
	{
		classification: "D",
		name: "Planetoid/Moon",
		canBeMoon: true,
		ageRange: { min: 20000000, max: 1000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None"],
		population: 0,
		radiusRange: { min: 50, max: 500 },
		zone: ["hot", "habitable", "cold"],
		temperatureRange: { min: 146, max: 400 },
		terranMassRange: { min: 0.01, max: 0.4 },
		hasClouds: 0,
		hasRings: 0,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/2k_moon.jpg",
			"/plugins/Thorium Default/assets/planets/Icy.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg",
		],
		possibleCloudMaps: [],
		possibleRingMaps,
	},
	{
		classification: "E",
		name: "Geoplastic",
		canBeMoon: true,
		ageRange: { min: 1000000, max: 2000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None"],
		population: 0,
		radiusRange: { min: 5000, max: 7500 },
		zone: ["habitable"],
		temperatureRange: { min: 800, max: 1443 },
		terranMassRange: { min: 0.1, max: 1.5 },
		hasClouds: 0,
		hasRings: 0,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureHot.jpg",
			"/plugins/Thorium Default/assets/planets/Volcanic.jpg",
		],
		possibleCloudMaps: [],
		possibleRingMaps,
	},
	{
		classification: "F",
		name: "Geometallic",
		canBeMoon: true,
		ageRange: { min: 1000000000, max: 3000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None"],
		population: 0,
		radiusRange: { min: 5000, max: 7500 },
		zone: ["habitable"],
		temperatureRange: { min: 500, max: 900 },
		terranMassRange: { min: 0.1, max: 1.5 },
		hasClouds: 0,
		hasRings: 0,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg",
		],
		possibleCloudMaps: [],
		possibleRingMaps,
	},
	{
		classification: "G",
		name: "Geocrystalline",
		canBeMoon: true,
		ageRange: { min: 3000000000, max: 4000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None", "Primitive single-celled organisms"],
		population: 0,
		radiusRange: { min: 5000, max: 7500 },
		zone: ["habitable"],
		temperatureRange: { min: 400, max: 600 },
		terranMassRange: { min: 0.5, max: 1.5 },
		hasClouds: 0,
		hasRings: 0,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/planet_textureCarbide.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureChlorine.jpg",
		],
		possibleCloudMaps: [],
		possibleRingMaps,
	},
	{
		classification: "H",
		name: "Desert",
		canBeMoon: true,
		ageRange: { min: 4000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None", "Primitive single-celled organisms", "Draught-resistant plants"],
		population: 0,
		radiusRange: { min: 4000, max: 7500 },
		zone: ["hot"],
		temperatureRange: { min: 500, max: 900 },
		terranMassRange: { min: 0.1, max: 1.5 },
		hasClouds: 0.7,
		hasRings: 0,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg",
		],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/clouds_textureSoft.png",
			"/plugins/Thorium Default/assets/clouds/Clouds1.png",
		],
		possibleRingMaps,
	},
	{
		classification: "I",
		name: "Gas Supergiant",
		ageRange: { min: 2000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None", "Floating single-celled lifeforms", "Hydrocarbon-based gas bag animals"],
		population: 0,
		radiusRange: { min: 70000, max: 5000000 },
		zone: ["cold"],
		temperatureRange: { min: 128, max: 340 },
		terranMassRange: { min: 300, max: 1000 },
		hasClouds: 0.4,
		hasRings: 0.8,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/2k_saturn.jpg",
			"/plugins/Thorium Default/assets/planets/2k_jupiter.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureFluorescent.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureBlueGiant.jpg",
		],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/clouds_textureGiant.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureSwept.png",
			"/plugins/Thorium Default/assets/clouds/Clouds4.png",
		],
		possibleRingMaps,
	},
	{
		classification: "J",
		name: "Gas Giant",
		ageRange: { min: 2000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: false,
		lifeforms: ["None", "Floating single-celled lifeforms", "Hydrocarbon-based gas bag animals"],
		population: 0,
		radiusRange: { min: 25000, max: 70000 },
		zone: ["cold"],
		temperatureRange: { min: 128, max: 340 },
		terranMassRange: { min: 10, max: 100 },
		hasClouds: 0.4,
		hasRings: 0.8,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/2k_neptune.jpg",
			"/plugins/Thorium Default/assets/planets/2k_uranus.jpg",
			"/plugins/Thorium Default/assets/planets/Gaseous2.jpg",
			"/plugins/Thorium Default/assets/planets/Gaseous1.jpg",
			"/plugins/Thorium Default/assets/planets/Gaseous3.jpg",
			"/plugins/Thorium Default/assets/planets/Gaseous4.jpg",
		],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/clouds_textureGiant.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureSwept.png",
			"/plugins/Thorium Default/assets/clouds/Clouds4.png",
		],
		possibleRingMaps,
	},
	{
		classification: "K",
		name: "Adaptable",
		canBeMoon: true,
		ageRange: { min: 4000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: true,
		lifeforms: ["None", "Primitive single-celled organisms"],
		population: { min: 0, max: 50000 },
		radiusRange: { min: 2500, max: 5000 },
		zone: ["habitable"],
		temperatureRange: { min: 117, max: 303 },
		terranMassRange: { min: 0.1, max: 1.5 },
		hasClouds: 0.4,
		hasRings: 0.2,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg",
			"/plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg",
		],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/Clouds1.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureSoft.png",
		],
		possibleRingMaps,
	},
	{
		classification: "L",
		name: "Martian",
		canBeMoon: true,
		ageRange: { min: 4000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: true,
		lifeforms: ["Primitive single-celled organisms", "Hardy plant life"],
		population: { min: 0, max: 50000 },
		radiusRange: { min: 2500, max: 7500 },
		zone: ["habitable"],
		temperatureRange: { min: 150, max: 330 },
		terranMassRange: { min: 0.1, max: 1.5 },
		hasClouds: 0.4,
		hasRings: 0.3,
		possibleTextureMaps: ["/plugins/Thorium Default/assets/planets/Martian.jpg"],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/Clouds1.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureSoft.png",
		],
		possibleRingMaps,
	},
	{
		classification: "M",
		name: "Terrestrial",
		canBeMoon: true,
		ageRange: { min: 3000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: true,
		lifeforms: ["Varied and extensive vegetation and animal life, humanoids"],
		population: { min: 10000000, max: 10000000000 },
		radiusRange: { min: 5000, max: 7500 },
		zone: ["habitable"],
		temperatureRange: { min: 288, max: 303 },
		terranMassRange: { min: 0.5, max: 1.5 },
		hasClouds: 1,
		hasRings: 0.5,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/Terrestrial1.jpg",
			"/plugins/Thorium Default/assets/planets/Terrestrial2.jpg",
			"/plugins/Thorium Default/assets/planets/Terrestrial3.jpg",
			"/plugins/Thorium Default/assets/planets/Terrestrial4.jpg",
		],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/Clouds1.png",
			"/plugins/Thorium Default/assets/clouds/Clouds2.png",
			"/plugins/Thorium Default/assets/clouds/Clouds3.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureSoft.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureMedium.png",
		],
		possibleRingMaps,
	},
	{
		classification: "N",
		name: "Venusian",
		canBeMoon: true,
		ageRange: { min: 3000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: true,
		lifeforms: ["Aquatic-based vegetation and animal life, humanoids"],
		population: { min: 5000000, max: 700000000 },
		radiusRange: { min: 5000, max: 7500 },
		zone: ["habitable"],
		temperatureRange: { min: 350, max: 735 },
		terranMassRange: { min: 0.5, max: 1.5 },
		hasClouds: 1,
		hasRings: 0.5,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/Venusian.jpg",
			"/plugins/Thorium Default/assets/planets/2k_venus_surface.jpg",
		],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/Clouds1.png",
			"/plugins/Thorium Default/assets/clouds/Clouds2.png",
			"/plugins/Thorium Default/assets/clouds/Clouds3.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureSoft.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureMedium.png",
		],
		possibleRingMaps,
	},
	{
		classification: "O",
		name: "Oceanic",
		canBeMoon: true,
		ageRange: { min: 3000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: true,
		lifeforms: ["Aquatic-based vegetation and animal life, humanoids"],
		population: { min: 5000000, max: 700000000 },
		radiusRange: { min: 5000, max: 7500 },
		zone: ["habitable"],
		temperatureRange: { min: 290, max: 303 },
		terranMassRange: { min: 0.5, max: 1.5 },
		hasClouds: 1,
		hasRings: 0.5,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/Tropical.jpg",
			"/plugins/Thorium Default/assets/planets/Swamp.jpg",
		],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/Clouds1.png",
			"/plugins/Thorium Default/assets/clouds/Clouds2.png",
			"/plugins/Thorium Default/assets/clouds/Clouds3.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureSoft.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureMedium.png",
		],
		possibleRingMaps,
	},
	{
		classification: "P",
		name: "Glaciated",
		canBeMoon: true,
		ageRange: { min: 3000000000, max: 10000000000 },
		atmosphericComposition: [],
		habitable: true,
		lifeforms: ["Hardy vegetation, animal life, humanoids"],
		population: { min: 20000, max: 200000 },
		radiusRange: { min: 5000, max: 7500 },
		zone: ["habitable"],
		temperatureRange: { min: 255, max: 270 },
		terranMassRange: { min: 0.5, max: 1.5 },
		hasClouds: 1,
		hasRings: 0.5,
		possibleTextureMaps: [
			"/plugins/Thorium Default/assets/planets/Icy.jpg",
			"/plugins/Thorium Default/assets/planets/Alpine.jpg",
		],
		possibleCloudMaps: [
			"/plugins/Thorium Default/assets/clouds/Clouds1.png",
			"/plugins/Thorium Default/assets/clouds/Clouds2.png",
			"/plugins/Thorium Default/assets/clouds/Clouds3.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureSoft.png",
			"/plugins/Thorium Default/assets/clouds/clouds_textureMedium.png",
		],
		possibleRingMaps,
	},
];
