// System names from Endless Sky and Ur Quan Masters
const SystemNames = [
	"Ablodab",
	"Ablub",
	"Acamar",
	"Achernar",
	"Acrux",
	"Adhara",
	"Aescolanus",
	"Al Dhanab",
	"Albaldah",
	"Albireo",
	"Alcor",
	"Alcyone",
	"Aldebaran",
	"Alderamin",
	"Aldhibain",
	"Algenib",
	"Algieba",
	"Algol",
	"Algorel",
	"Alheka",
	"Alhena",
	"Alioth",
	"Alkaid",
	"Almaaz",
	"Almach",
	"Almagest",
	"Alnair",
	"Alnasl",
	"Alnilam",
	"Alnitak",
	"Alniyat",
	"Alpha Andromedae",
	"Alpha Antliae",
	"Alpha Apodis",
	"Alpha Aquarii",
	"Alpha Aquilae",
	"Alpha Arae",
	"Alpha Arianni",
	"Alpha Arietis",
	"Alpha Aurigae",
	"Alpha Bootis",
	"Alpha Brahe",
	"Alpha Caeli",
	"Alpha Camelopardalis",
	"Alpha Cancri",
	"Alpha Capricorni",
	"Alpha Carinae",
	"Alpha Cassiopeiae",
	"Alpha Centauri",
	"Alpha Cephei",
	"Alpha Cerenkov",
	"Alpha Ceti",
	"Alpha Chamaeleonis",
	"Alpha Chandrasekhar",
	"Alpha Circini",
	"Alpha Columbae",
	"Alpha Copernicus",
	"Alpha Crateris",
	"Alpha Crucis",
	"Alpha Cygnus",
	"Alpha Delphini",
	"Alpha Doradus",
	"Alpha Draconis",
	"Alpha Equulei",
	"Alpha Eridani",
	"Alpha Fornacis",
	"Alpha Geminorum",
	"Alpha Giclas",
	"Alpha Gorno",
	"Alpha Gruis",
	"Alpha Herculis",
	"Alpha Horologii",
	"Alpha Hyades",
	"Alpha Hydrae",
	"Alpha Hydri",
	"Alpha Hyginus",
	"Alpha Illuminati",
	"Alpha Indi",
	"Alpha Kepler",
	"Alpha Klystron",
	"Alpha Krueger",
	"Alpha Lacaille",
	"Alpha Lacertae",
	"Alpha Lalande",
	"Alpha Lentelis",
	"Alpha Leonis",
	"Alpha Leporis",
	"Alpha Librae",
	"Alpha Lipi",
	"Alpha Luyten",
	"Alpha Lyncis",
	"Alpha Lyrae",
	"Alpha Maksutov",
	"Alpha Mensae",
	"Alpha Mersenne",
	"Alpha Mira",
	"Alpha Monocerotis",
	"Alpha Muscae",
	"Alpha Normae",
	"Alpha Octantis",
	"Alpha Olber",
	"Alpha Ophiuchi",
	"Alpha Orionis",
	"Alpha Pavonis",
	"Alpha Pegasi",
	"Alpha Persei",
	"Alpha Phoenicis",
	"Alpha Pictoris",
	"Alpha Piscium",
	"Alpha Ptolemae",
	"Alpha Puppis",
	"Alpha Pyxidis",
	"Alpha Raynet",
	"Alpha Reticuli",
	"Alpha Sagittae",
	"Alpha Sagittarii",
	"Alpha Saurus",
	"Alpha Scorpii",
	"Alpha Sculptoris",
	"Alpha Scuti",
	"Alpha Serpentis",
	"Alpha Sextantis",
	"Alpha Squidi",
	"Alpha Tauri",
	"Alpha Telescopii",
	"Alpha Trianguli",
	"Alpha Tucanae",
	"Alpha Velorum",
	"Alpha Virginis",
	"Alpha Vitalis",
	"Alpha Volantis",
	"Alpha Vulpeculae",
	"Alpha Wolf",
	"Alphard",
	"Alphecca",
	"Alpheratz",
	"Altair",
	"Aludra",
	"Ancient Hope",
	"Ankaa",
	"Answer",
	"Antablian",
	"Antares",
	"Antevorta",
	"Ap'arak",
	"Arcturus",
	"Arculus",
	"Arneb",
	"Ascella",
	"Asikafarnut",
	"Aspidiske",
	"Atria",
	"Avior",
	"Aya'k'k",
	"Beginning",
	"Bellatrix",
	"Belonging",
	"Belug",
	"Belugt",
	"Beta Andromedae",
	"Beta Antliae",
	"Beta Apodis",
	"Beta Aquarii",
	"Beta Aquilae",
	"Beta Arae",
	"Beta Arianni",
	"Beta Arietis",
	"Beta Aurigae",
	"Beta Bootis",
	"Beta Brahe",
	"Beta Caeli",
	"Beta Camelopardalis",
	"Beta Cancri",
	"Beta Capricorni",
	"Beta Carinae",
	"Beta Cassiopeiae",
	"Beta Centauri",
	"Beta Cephei",
	"Beta Cerenkov",
	"Beta Ceti",
	"Beta Chamaeleonis",
	"Beta Chandrasekhar",
	"Beta Circini",
	"Beta Columbae",
	"Beta Copernicus",
	"Beta Corvi",
	"Beta Crateris",
	"Beta Crucis",
	"Beta Cygnus",
	"Beta Delphini",
	"Beta Doradus",
	"Beta Draconis",
	"Beta Equulei",
	"Beta Eridani",
	"Beta Fornacis",
	"Beta Geminorum",
	"Beta Giclas",
	"Beta Gorno",
	"Beta Gruis",
	"Beta Herculis",
	"Beta Horologii",
	"Beta Hyades",
	"Beta Hydrae",
	"Beta Hyginus",
	"Beta Illuminati",
	"Beta Indi",
	"Beta Kepler",
	"Beta Klystron",
	"Beta Krueger",
	"Beta Lacaille",
	"Beta Lacertae",
	"Beta Lalande",
	"Beta Lentelis",
	"Beta Leonis",
	"Beta Leporis",
	"Beta Librae",
	"Beta Lipi",
	"Beta Lupi",
	"Beta Luyten",
	"Beta Lyncis",
	"Beta Lyrae",
	"Beta Maksutov",
	"Beta Mensae",
	"Beta Mersenne",
	"Beta Mira",
	"Beta Monocerotis",
	"Beta Muscae",
	"Beta Normae",
	"Beta Octantis",
	"Beta Olber",
	"Beta Ophiuchi",
	"Beta Orionis",
	"Beta Pavonis",
	"Beta Pegasi",
	"Beta Persei",
	"Beta Phoenicis",
	"Beta Pictoris",
	"Beta Piscium",
	"Beta Ptolemae",
	"Beta Puppis",
	"Beta Pyxidis",
	"Beta Raynet",
	"Beta Reticuli",
	"Beta Sagittae",
	"Beta Sagittarii",
	"Beta Saurus",
	"Beta Scorpii",
	"Beta Scuti",
	"Beta Serpentis",
	"Beta Sextantis",
	"Beta Squidi",
	"Beta Tauri",
	"Beta Telescopii",
	"Beta Trianguli",
	"Beta Tucanae",
	"Beta Velorum",
	"Beta Virginis",
	"Beta Vitalis",
	"Beta Volantis",
	"Beta Vulpeculae",
	"Beta Wolf",
	"Betelgeuse",
	"Bloptab",
	"Blubipad",
	"Blugtad",
	"Boral",
	"Bore Fah",
	"Bote Asu",
	"Bright Void",
	"Broken Bowl",
	"Caeculus",
	"Canopus",
	"Capella",
	"Caph",
	"Cardax",
	"Cardea",
	"Castor",
	"Cebalrai",
	"Celeborim",
	"Chikatip",
	"Chimitarp",
	"Chirr'ay'akai",
	"Chornifath",
	"Chy'chra",
	"Cinxia",
	"Coluber",
	"Columbae",
	"Companion",
	"Convector",
	"Cor Caroli",
	"Da Ent",
	"Da Lest",
	"Dabih",
	"Danoa",
	"Dark Hills",
	"Debrugt",
	"Delta Antliae",
	"Delta Apodis",
	"Delta Aquarii",
	"Delta Aquilae",
	"Delta Arae",
	"Delta Arietis",
	"Delta Aurigae",
	"Delta Bootis",
	"Delta Brahe",
	"Delta Caeli",
	"Delta Camelopardalis",
	"Delta Cancri",
	"Delta Capricorni",
	"Delta Cassiopeiae",
	"Delta Centauri",
	"Delta Ceti",
	"Delta Chamaeleonis",
	"Delta Chandrasekhar",
	"Delta Circini",
	"Delta Corvi",
	"Delta Crateris",
	"Delta Crucis",
	"Delta Cygnus",
	"Delta Draconis",
	"Delta Fornacis",
	"Delta Geminorum",
	"Delta Giclas",
	"Delta Gorno",
	"Delta Gruis",
	"Delta Horologii",
	"Delta Hyades",
	"Delta Illuminati",
	"Delta Krueger",
	"Delta Lalande",
	"Delta Lentelis",
	"Delta Librae",
	"Delta Lipi",
	"Delta Lyncis",
	"Delta Mira",
	"Delta Muscae",
	"Delta Normae",
	"Delta Orionis",
	"Delta Persei",
	"Delta Pictoris",
	"Delta Piscium",
	"Delta Ptolemae",
	"Delta Reticuli",
	"Delta Sagittarii",
	"Delta Scorpii",
	"Delta Sculptoris",
	"Delta Scuti",
	"Delta Serpentis",
	"Delta Sextantis",
	"Delta Tauri",
	"Delta Velorum",
	"Delta Virginis",
	"Delta Vitalis",
	"Delta Volantis",
	"Delta Vulpeculae",
	"Deneb",
	"Denebola",
	"Diphda",
	"Dokdobaru",
	"Dschubba",
	"Dubhe",
	"Due Yoot",
	"Durax",
	"Eber",
	"Eblumab",
	"Edusa",
	"Ehma Ti",
	"Ek'kek'ru",
	"Ekuarik",
	"Elnath",
	"Eltanin",
	"Eneremprukt",
	"Enif",
	"Epsilon Antliae",
	"Epsilon Aquarii",
	"Epsilon Aquilae",
	"Epsilon Arae",
	"Epsilon Arietis",
	"Epsilon Bootis",
	"Epsilon Brahe",
	"Epsilon Caeli",
	"Epsilon Camelopardalis",
	"Epsilon Cassiopeiae",
	"Epsilon Centauri",
	"Epsilon Ceti",
	"Epsilon Chamaeleonis",
	"Epsilon Chandrasekhar",
	"Epsilon Circini",
	"Epsilon Corvi",
	"Epsilon Crateris",
	"Epsilon Cygnus",
	"Epsilon Draconis",
	"Epsilon Fornacis",
	"Epsilon Giclas",
	"Epsilon Gorno",
	"Epsilon Gruis",
	"Epsilon Horologii",
	"Epsilon Hyades",
	"Epsilon Illuminati",
	"Epsilon Krueger",
	"Epsilon Leonis",
	"Epsilon Librae",
	"Epsilon Lipi",
	"Epsilon Lyncis",
	"Epsilon Muscae",
	"Epsilon Normae",
	"Epsilon Orionis",
	"Epsilon Persei",
	"Epsilon Ptolemae",
	"Epsilon Scorpii",
	"Epsilon Sculptoris",
	"Epsilon Scuti",
	"Epsilon Serpentis",
	"Epsilon Sextantis",
	"Epsilon Tauri",
	"Epsilon Volantis",
	"Epsilon Vulpeculae",
	"Es'sprak'ai",
	"Eshkoshtar",
	"Eta Aquarii",
	"Eta Bootis",
	"Eta Camelopardalis",
	"Eta Ceti",
	"Eta Chamaeleonis",
	"Eta Corvi",
	"Eta Crateris",
	"Eta Draconis",
	"Eta Fornacis",
	"Eta Giclas",
	"Eta Gruis",
	"Eta Horologii",
	"Eta Hyades",
	"Eta Illuminati",
	"Eta Librae",
	"Eta Lyncis",
	"Eta Orionis",
	"Eta Persei",
	"Eta Ptolemae",
	"Eta Serpentis",
	"Eta Volantis",
	"Eta Vulpeculae",
	"Eteron",
	"Fah Root",
	"Fah Soom",
	"Fala",
	"Fallen Leaf",
	"Far Horizon",
	"Farbutero",
	"Farinus",
	"Faronektu",
	"Fasitopfar",
	"Fell Omen",
	"Feroteri",
	"Ferukistek",
	"Fingol",
	"Flugbu",
	"Fomalhaut",
	"Fornarep",
	"Four Pillars",
	"Furmeliki",
	"Gacrux",
	"Gamma Antliae",
	"Gamma Apodis",
	"Gamma Aquarii",
	"Gamma Aquilae",
	"Gamma Arae",
	"Gamma Arianni",
	"Gamma Arietis",
	"Gamma Aurigae",
	"Gamma Bootis",
	"Gamma Brahe",
	"Gamma Caeli",
	"Gamma Camelopardalis",
	"Gamma Cancri",
	"Gamma Capricorni",
	"Gamma Carinae",
	"Gamma Cassiopeiae",
	"Gamma Centauri",
	"Gamma Ceti",
	"Gamma Chamaeleonis",
	"Gamma Chandrasekhar",
	"Gamma Circini",
	"Gamma Columbae",
	"Gamma Copernicus",
	"Gamma Corvi",
	"Gamma Crateris",
	"Gamma Crucis",
	"Gamma Cygnus",
	"Gamma Draconis",
	"Gamma Eridani",
	"Gamma Fornacis",
	"Gamma Geminorum",
	"Gamma Giclas",
	"Gamma Gorno",
	"Gamma Gruis",
	"Gamma Horologii",
	"Gamma Hyades",
	"Gamma Hydrae",
	"Gamma Illuminati",
	"Gamma Kepler",
	"Gamma Krueger",
	"Gamma Lacaille",
	"Gamma Lalande",
	"Gamma Lentelis",
	"Gamma Leonis",
	"Gamma Leporis",
	"Gamma Librae",
	"Gamma Lipi",
	"Gamma Luyten",
	"Gamma Lyncis",
	"Gamma Mensae",
	"Gamma Mira",
	"Gamma Muscae",
	"Gamma Normae",
	"Gamma Olber",
	"Gamma Ophiuchi",
	"Gamma Orionis",
	"Gamma Persei",
	"Gamma Phoenicis",
	"Gamma Pictoris",
	"Gamma Piscium",
	"Gamma Ptolemae",
	"Gamma Puppis",
	"Gamma Pyxidis",
	"Gamma Raynet",
	"Gamma Reticuli",
	"Gamma Sagittae",
	"Gamma Sagittarii",
	"Gamma Saurus",
	"Gamma Scorpii",
	"Gamma Sculptoris",
	"Gamma Scuti",
	"Gamma Serpentis",
	"Gamma Sextantis",
	"Gamma Squidi",
	"Gamma Tauri",
	"Gamma Telescopii",
	"Gamma Trianguli",
	"Gamma Tucanae",
	"Gamma Virginis",
	"Gamma Vitalis",
	"Gamma Volantis",
	"Gamma Vulpeculae",
	"Gienah",
	"Girtab",
	"Glubatub",
	"Gomeisa",
	"Good Omen",
	"Gorvi",
	"Graffias",
	"Groombridge",
	"Gupta",
	"Hadar",
	"Hamal",
	"Han",
	"Hassaleh",
	"Hatysa",
	"Heia Due",
	"Hesselpost",
	"Hevru Hai",
	"Hi Yahr",
	"Hintar",
	"Holeb",
	"Homeward",
	"Host",
	"Hunter",
	"Hyperion",
	"Ik'kara'ka",
	"Ildaria",
	"Imo Dep",
	"Insitor",
	"Io Lowe",
	"Io Mann",
	"Iota Camelopardalis",
	"Iota Chamaeleonis",
	"Iota Draconis",
	"Iota Horologii",
	"Iota Hyades",
	"Iota Orionis",
	"Iota Persei",
	"Iota Serpentis",
	"Ipsing",
	"Iyech'yek",
	"Izar",
	"Ka'ch'chrai",
	"Ka'pru",
	"Kaliptari",
	"Kappa Centauri",
	"Kappa Chamaeleonis",
	"Kappa Draconis",
	"Kappa Horologii",
	"Kappa Hyades",
	"Kappa Orionis",
	"Kashikt",
	"Kasikfar",
	"Kaus Australis",
	"Kaus Borealis",
	"Ki War Ek",
	"Kiro'ku",
	"Kiru'kichi",
	"Kochab",
	"Kor Ak'Mari",
	"Kor En'lakfar",
	"Kor Fel'tar",
	"Kor Men",
	"Kor Nor'peli",
	"Kor Tar'bei",
	"Kor Zena'i",
	"Kornephoros",
	"Korsmanath",
	"Kraz",
	"Kugel",
	"Kursa",
	"Lambda Draconis",
	"Lambda Horologii",
	"Lambda Hyades",
	"Lambda Orionis",
	"Last Word",
	"Lesath",
	"Levana",
	"Limen",
	"Lolami",
	"Lom Tahr",
	"Lone Cloud",
	"Lucina",
	"Lurata",
	"Makferuti",
	"Markab",
	"Markeb",
	"Matar",
	"Mebla",
	"Mebsuta",
	"Meftarkata",
	"Mei Yohn",
	"Mekislepti",
	"Membulem",
	"Men",
	"Menkalinan",
	"Menkar",
	"Menkent",
	"Merak",
	"Mesuket",
	"Metis",
	"Miaplacidus",
	"Miblulub",
	"Microscopii",
	"Mimosa",
	"Minkar",
	"Mintaka",
	"Mirach",
	"Mirfak",
	"Mirzam",
	"Mizar",
	"Moktar",
	"Mora",
	"Mu Draconis",
	"Mu Orionis",
	"Muhlifain",
	"Muphrid",
	"Naos",
	"Naper",
	"Nenia",
	"Nihal",
	"Nocte",
	"Nu Draconis",
	"Nunki",
	"Oblate",
	"Orbona",
	"Organon",
	"Orvala",
	"Ossipago",
	"Pantica",
	"Parca",
	"Peacock",
	"Pelubta",
	"Peragenor",
	"Peresedersi",
	"Perfica",
	"Persian",
	"Persitar",
	"Phact",
	"Phecda",
	"Pherkad",
	"Phurad",
	"Pik'ro'iyak",
	"Plort",
	"Polaris",
	"Pollux",
	"Porrima",
	"Prakacha'a",
	"Procyon",
	"Pug Iyik",
	"Quaru",
	"Rajak",
	"Rasalhague",
	"Rastaban",
	"Rati Cal",
	"Regor",
	"Regulus",
	"Remembrance",
	"Rigel",
	"Ruchbah",
	"Rutilicus",
	"Sabik",
	"Sabriset",
	"Sadalmelik",
	"Sadalsuud",
	"Sadr",
	"Saiph",
	"Salipastart",
	"Sargas",
	"Sarin",
	"Sayaiban",
	"Scheat",
	"Schedar",
	"Segesta",
	"Seginus",
	"Seketra",
	"Sepetrosk",
	"Sepriaptu",
	"Sevrelect",
	"Shaula",
	"Sheratan",
	"Si'yak'ku",
	"Sich'ka'ara",
	"Silikatakfar",
	"Silver Bell",
	"Silver String",
	"Similisti",
	"Sirius",
	"Skeruto",
	"Sko'karak",
	"Sobarati",
	"Sol",
	"Solifar",
	"Sospi",
	"Speloog",
	"Spica",
	"Steep Roof",
	"Stercutus",
	"Suhail",
	"Sumar",
	"Sumprast",
	"Tais",
	"Talita",
	"Tania Australis",
	"Tarazed",
	"Tebuteb",
	"Tejat",
	"Terminus",
	"Theta Camelopardalis",
	"Theta Chamaeleonis",
	"Theta Crateris",
	"Theta Draconis",
	"Theta Giclas",
	"Theta Horologii",
	"Theta Hyades",
	"Theta Illuminati",
	"Theta Lyncis",
	"Theta Orionis",
	"Theta Persei",
	"Theta Serpentis",
	"Torbab",
	"Tortor",
	"Turais",
	"Ula Mon",
	"Ultima Thule",
	"Umbral",
	"Unagi",
	"Unukalhai",
	"Uwa Fahn",
	"Vega",
	"Vela",
	"Vindemiatrix",
	"Volax",
	"Wah Ki",
	"Wah Oh",
	"Wah Yoot",
	"Waypoint",
	"Wazn",
	"Wei",
	"Wezen",
	"Xi Draconis",
	"Ya Hai",
	"Yed Prior",
	"Zaurak",
	"Zeeman",
	"Zeta Antliae",
	"Zeta Aquarii",
	"Zeta Aquilae",
	"Zeta Bootis",
	"Zeta Brahe",
	"Zeta Camelopardalis",
	"Zeta Centauri",
	"Zeta Ceti",
	"Zeta Chamaeleonis",
	"Zeta Circini",
	"Zeta Corvi",
	"Zeta Crateris",
	"Zeta Draconis",
	"Zeta Fornacis",
	"Zeta Giclas",
	"Zeta Gruis",
	"Zeta Horologii",
	"Zeta Hyades",
	"Zeta Illuminati",
	"Zeta Krueger",
	"Zeta Librae",
	"Zeta Lyncis",
	"Zeta Muscae",
	"Zeta Normae",
	"Zeta Orionis",
	"Zeta Persei",
	"Zeta Ptolemae",
	"Zeta Scorpii",
	"Zeta Scuti",
	"Zeta Serpentis",
	"Zeta Sextantis",
	"Zeta Tauri",
	"Zeta Volantis",
	"Zeta Vulpeculae",
	"Zosma",
	"Zubenelgenubi",
	"Zubeneschamali",
	// Stars named by Ryan Anderson
	"Hyperborea",
	"Tau Ceti",
	"Arcadia",
	"Thuban",
	"Thule",
	"Girallon",
	"Immolith",
	"Kunlun",
	"Chuul",
	"Uru",
	"Dorsai",
	"Naraka",
	"Avalon",
	"Cytheria",
	"Zyzyx",
	"Olympus",
	"Tartarus",
	"Phane",
	"Galadon",
	"Manu",
	"Valhalla",
	"Dathyl",
	"Jinx",
	"Cordia",
	"Elysium",
	"Ikari",
	"Pelandria",
	"Ephemera",
	"Grell",
	"Gwystil",
	// Stars named by Brent Anderson
	"Beeblebrox",
	"Mendon",
];

export default SystemNames;
