name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Lint
        run: |
          bun run lint
      - name: TypeCheck
        run: |
          bun run typecheck
      - name: Test
        run: |
          bun run test
